### PR TITLE
all: Compare state ingested using expingest with stellar-core

### PR DESCRIPTION
**Pull request by bartekn**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### Summary

This PR adds a new job and nightly workflow to compare state ingested using `SingleLedgerStateReader` with an actual state in Stellar-Core DB.

### Goal and scope

In #1550 we are building a tool to periodically compare state in Horizon DB vs state in history archives. This way we can find if the state updated using txmeta is the same as in buckets for a given checkpoint. However, in case there is a bug in `SingleLedgerStateReader` the check may succeed even though the state is actually invalid. We have good tests for `SingleLedgerStateReader` but it's always better to be safe than sorry.

Initially this was supposed to be a nightly workflow run once a day however I was surprised that it's actually able to complete in around 5 minutes so I decided to add is as a regular, non-required job for commits in `master` and Horizon release branches. Let me know if it's fine.

This is the last [run](https://circleci.com/gh/stellar/go/7202) before changing Circle config file to the final state (where this job is not run in this PR branch).

### Summary of changes

* Added a new commands, jobs and workflow to CircleCI config.
* Updated scripts in `exp/tools/dump-ledger-state/run_test.sh` to work in any environment (not only on my machine).

### Known limitations & issues

* We could make this job even faster by parallelising ingesting state and stellar-core catchup however it's a little bit complicated to do.

### CODE REVIEW

**Comment by tamirms** [comment]
why isn't exp/tools/dump-ledger-state/run_test.sh used by the CircleCI build?

**Comment by bartekn** [comment]
> why isn't exp/tools/dump-ledger-state/run_test.sh used by the CircleCI build?

No good reason other than that I wanted to actually run "Dump state using ingest" and "Catchup core" in parallel but when I started checking the docs it was much more complicated. I think I will improve it in a less busy sprint. What's also nice about this vs all-in-one script in Circle is that it's more readable (each `run` is in a separate section). However I can change it to `run_test.sh`.

**Comment by ire-and-curses** [comment]
This is cool. Is it true that once the state goes out of sync, it will fail for all subsequent builds? I want to make sure we're able to notice this failing.

**Comment by bartekn** [comment]
> Is it true that once the state goes out of sync, it will fail for all subsequent builds (with future ledgers)?

Not always. It depends on the bug, it can manifest itself in some checkpoints but not in the others. Which makes this:
> I want to make sure we're able to notice this failing.

important because a new job is executed only nightly, in `master` and Horizon release branches. So I'm wondering if Circle will send notifications and who will received them (author of the latest commit?). Maybe we should send a slack notification on failures? What do you think @ire-and-curses?

Also, since it only takes 5-6 minutes, we should run it more often. The problem is that in Circle:
> Note: Cron step syntax (for example, */1, */20) is not supported. Range elements within comma-separated lists of elements are also not supported.

This would require us to add, say, 24 different workflows to run this every hour in Circle.

**Comment by bartekn** [comment]
> Also, since it only takes 5-6 minutes, we should run it more often.

Actually, we could run it for each checkpoint ledger because they are created every 5 minutes (with a potential to shorten tests to 3 minutes when we run jobs in parallel, there should be no delays when using a single process).

**Comment by ire-and-curses** [comment]
Hmm. I guess I'm worried that we're using Circle in a way that isn't intended. It's nice to have a job run as a sanity check on build, or nightly, but based on this discussion we need to run it against *every* ledger or bugs can still slip through. I take your point that if the job was parallelised it might be generally fast enough. I don't like the idea of creating 24 workflows! :( Also the [Circle docs](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow) say:

> Note: Scheduled workflows may be delayed by up to 15 minutes. This is done to maintain reliability during busy times such as 12:00am UTC. Scheduled workflows should not assume they are started with to-the-minute accuracy.

So it's possible that ledgers could be missed, although it's probably rare.

The odd part is that this isn't really an integration test in the normal sense - it's a continuously running validation against incoming data, and it could fail even with no code changes. That makes me wonder whether we should consider another way to run this (e.g. on a dev box or lambda). What are your thoughts @bartekn @tamirms?

**Comment by tamirms** [comment]
I think you could implement this as kubernetes cron job:

https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

**Comment by bartekn** [comment]
Yes, I agree Circle shouldn't be used for continuous test (however it's nice to have a nightly and branch releases here to catch some bugs not covered by unit tests).

AWS Lambda is definitely not a a good idea too for many reasons (we would probably need to run postgres externally, 512MB max disk storage - a single `account.csv` alone is almost 400MB now).

Good idea from @tamirms to test our new Kubernetes cluster! 👍

**Comment by ire-and-curses** [comment]
Ok - raised #1687 to track this.

**Pull request merged**
