### PR TITLE
services/horizon/internal/integration: Conservatively limit the number of DB connections of integration tests

### PR DESCRIPTION
**Pull request by 2opremio**
This will likely fix recent integration test problems like https://github.com/stellar/go/runs/6233228705:

```
 time="2022-04-29T18:45:37.239Z" level=error msg="Error starting ingestion read transaction: beginTx failed: pq: sorry, too many clients already" pid=5821 req=fv-az206-0/Br5gxfz9Ua-000971 stack="[main.go:43 middleware.go:330 server.go:2047 chain.go:31 mux.go:425 server.go:2047 mux.go:70 mux.go:292 server.go:2047 mux.go:425 server.go:2047 mux.go:70 mux.go:292 server.go:2047 chain.go:31 mux.go:425 server.go:2047 cors.go:190 server.go:2047 compress.go:190 server.go:2047 middleware.go:228 server.go:2047 middleware.go:111 server.go:2047 middleware.go:84 server.go:2047 xff_middleware.go:51 server.go:2047 middleware.go:48 server.go:2047 request_id.go:76]"
 ```

### CODE REVIEW

**Review by bartekn — APPROVED** [review]

**Comment by 2opremio** [comment]
This clearly doesn't solve the problem since we just got the same error. I am out of ideas for now.

**Comment by 2opremio** [comment]
@sreuland Would https://github.com/stellar/go/pull/4185 solve that problem?

**Comment by 2opremio** [comment]
I am going to merge this anyhow, since it shouldn't hurt

**Comment by sreuland** [comment]
> @sreuland Would #4185 solve that problem?

it looks like it may have stumbled into one way to resolve unclosed/leaked sessions by [calling the historyQ.Close() within ingest.Shutdown()](https://github.com/stellar/go/pull/4185/files#diff-933b9cab99da778822646614e836dc6c6b0cae788d582b977e896c86a67bd5d8R700) , but @bartekn warned on using that approach coupled the ingest lifecycle too much into shutdown order of other components.

all sessions had to be closed or the `drop db` statement at end of test would fail, so that led to some investigation and observing in PGAdmin the unclosed db sessions left even after integration test had invoked the various shutdown methods including App.Shutdown(), the unclosed session appeared to be originating from db sessions initiated within Ingest.

**Pull request merged**
