### PR TITLE
all: Switch over from CircleCI to GitHub Actions

### PR DESCRIPTION
**Pull request by 2opremio**
Closes https://github.com/stellar/go/issues/4229

### CODE REVIEW

**Review by leighmcculloch — APPROVED** [review]

**Comment by 2opremio** [comment]
@leighmcculloch I think we also need to disable circleci somehow? Note how there was an attempt to run the jobs even if they were removed.

**Comment by leighmcculloch** [comment]
@stellar/ops-team Can help with that.

**Comment by 2opremio** [comment]
@jacekn this is now merged, can you please remove the integration with CircleCI in the repo? Otherwise we are going to get errors becase there are not CircleCI config files.

**Comment by jacekn** [comment]
> @jacekn this is now merged, can you please remove the integration with CircleCI in the repo? Otherwise we are going to get errors becase there are not CircleCI config files.

This has been done!

**Comment by 2opremio** [comment]
Awesome, thanks @jacekn !

**Pull request merged**
