### PR TITLE
all: Bump XDR for soroban-pubnet release

### PR DESCRIPTION
**Pull request by 2opremio**
Update XDR to [`6a620d160aab22609c982d54578ff6a63bfcdc01`](https://github.com/stellar/stellar-xdr/tree/6a620d160aab22609c982d54578ff6a63bfcdc01)

Integration tests won't pass until soroban-rpc is updated and bumped in this repo.

### CODE REVIEW

**Comment by tamirms** [comment]
@2opremio I have retarted the PR to land on the pubnet release branch [release-horizon-v2.27.0](https://github.com/stellar/go/tree/release-horizon-v2.27.0)

**Comment by tamirms** [comment]
@2opremio can you rebase so the pr only contains the xdr update?

**Comment by 2opremio** [comment]
Sure!

**Review by tamirms — APPROVED** [review]

**Comment by tsachiherman** [comment]
There are quite many `ST1003: method SetTtl should be SetTTL (stylecheck)` -style warning coming from the linter.
( see `file changed` tab )

**Comment by Shaptic** [comment]
@2opremio according to [this thread](https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1697477264919129) the SHA should be https://github.com/stellar/stellar-xdr/commit/6a620d160aab22609c982d54578ff6a63bfcdc01

**Comment by 2opremio** [comment]
> ~@2opremio according to [this thread](https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1697477264919129) the SHA should be [stellar/stellar-xdr@6a620d1](https://github.com/stellar/stellar-xdr/commit/6a620d160aab22609c982d54578ff6a63bfcdc01)~
> 
> Jk I see you did that in [c7d3a47](https://github.com/stellar/go/commit/c7d3a47ee7a2cf57755cb76ed60067b138310614). Don't forget to update the description/merge commit message!

Done!

**Pull request merged**
