### PR TITLE
services/horizon: Update goautoneg dep to not use BitBucket repo.

### PR DESCRIPTION
**Pull request by Shaptic**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What
Go modules have been updated to replace a [necessary dependency](https://github.com/adjust/goautoneg/).

### Why
BitBucket dropped the one we used previously because it was a Mercurial repository (see #2039).

### CODE REVIEW

**Comment by ire-and-curses** [comment]
@cla-bot check

**Review by bartekn — APPROVED** [review]
LGTM! Congrats on your first Horizon PR! 🎊

**Comment by BRBussy** [comment]
Hi everyone! Is any idea on a timeline for when this dependency update will become available in a new _horizonclient/txnbuild_ release? From what I can see this change is not yet available in the [latest release](https://github.com/stellar/go/releases/tag/horizonclient-v3.2.0) of the client libraries.

Please let me know if I am misunderstanding something and there is a way to use the latest client libraries release with the updated depenency.

**Comment by ire-and-curses** [comment]
@BRBussy you're right, we neglected to release this.

There will be a release of the client next week (with support for upcoming protocol 14). It will include this dependency fix.

**Comment by BRBussy** [comment]
Hi @ire-and-curses thank you so much for the update - it is certainly much appreciated. Will keep an eye out for that release. Looking forward to it, particularly protocol 14 support. Have a great day!

**Comment by afrizuko** [comment]
Hi everyone! Was this fix released. I'm getting a missing client library (clients/horizon) when using the latest version.

**Comment by Shaptic** [comment]
This fix has been released as of [v4.0.0](https://github.com/stellar/go/releases/tag/horizonclient-v4.0.0) (note [the diff](https://github.com/stellar/go/compare/horizonclient-v3.2.0...horizonclient-v4.0.0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6) from v3.2.0)

I'm not sure if there's a typo in your comment, but the client library is `clients/horizonclient`. Feel free to raise a separate issue if you're still encountering problems.

**Comment by afrizuko** [comment]
Thanks @Shaptic I checked it. Had to upgrade to the latest and perform some refactoring. Thanks again!

**Pull request merged**
