### PR TITLE
all: Use Go module machinery to book-keep external tools

### PR DESCRIPTION
**Pull request by 2opremio**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Track and maintain external tooling through Go's module machinery.

For that, I am using a [`tools.go`](https://github.com/golang/go/issues/25922#issuecomment-412992431) file, which seems to be an increasingly-adopted practice.

### Why

1. It centralizes version tracking of tooling instead of having versions spread around in shell-scripts
2. Where possible (if performance allows it) it saves developers from installing external tools, by using `go run`, making things work transparently (e.g. it took me a while to find out that the specific version of `go-bindata` to use was buried in `gogenerate.sh`)

### Known limitations

`go run` is slower than running a  binary (at least until https://github.com/golang/go/issues/33468 is resolved), so we need to be careful on where to use it (e.g. the `shadow` binary is installed because `go run` is too slow).

### CODE REVIEW

**Comment by 2opremio** [comment]
@leighmcculloch are we planning to break out the code base into different modules? If so, do you know when and where?

Also, regardless of this PR, the Go SDK should be its own module, so that it doesn't drag all the other dependencies.

Once that is done we can evaluate whether it makes sense to push this trick to the new modules or roll it back. Until then (based on the approvals in this PR) I think there is consensus on moving forward with this approach.

**Comment by leighmcculloch** [comment]
There are plans to do it yup, see go modules [part 1](https://docs.google.com/document/d/1v9HXRSjI7L-JypoMf80_qeotXn2gfp0LnPxToZfr87k) and [part 2](https://docs.google.com/document/d/1-DytA21WTP-VXMl_mULGadwKe9LzgGKipyedDf0ul5U) documents. We've done part 1, haven't done part 2 yet.

I think it is worth considering this after part 2 if the tools.go can live in its own module so that it doesn't pollute any other module. In fact you could probably introduce just that one module now independent of part 2.

**Comment by ire-and-curses** [comment]
@2opremio Yeah this is a plan we've had for a while but haven't had bandwidth to execute. I'd love it if you took some time to read through the links @leighmcculloch shared and then we can discuss what we want to do about it, and when. For now I think we should pause this PR to keep the Go SDK deps frozen. Happy to discuss early next week.

**Comment by 2opremio** [comment]
I still need to look at this, but I think we can close it

**Pull request closed without merging**
