### PR TITLE
services/horizon: added indexes by id for cb and liquidity pool on tx/ops tables

### LINKED ISSUE #4455: Optimize history tables for query by id performance(claimable balance, accounts, liquidity pools and assets)
### What version are you using?

Horizon 2.18.1

### What did you do?

https://horizon.stellar.org/claimable_balances/0000000028b32c721976af53fa0419eba129f3da70168f1e39822a25886375abad9599da/transactions?limit=1&order=asc

### What did you expect to see?
list of transactions related to entity returned in reasonably fast response time

list of tx's by entity covers a few types that can be vulnerable to this query path behavior, 'claimable balance', 'accounts', 'liquidity pool', 'assets', want to include optimization for each of these as they likely have same root cause in query performance.

### What did you see instead?
503, timeout responses.

### PR DESCRIPTION
**Pull request by sreuland**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

added indexes on the cb and liquidity pool id columns in their respective tx/ops materialized join tables

### Why

there were slow query performance happening after growth of these tables, and some queries were joining on the id itself which wasn't indexed yet, waiting on long table scans.
Closes #4455 

### Known limitations

N/A

### CODE REVIEW

**Comment by sreuland** [comment]
I looked into a few other candidates, `history_assets` table didn't see need for further indexing, and accounts via `history_transaction_participants` and `history_operation_participants`, those tables have a compound index that starts with `history_account_id`, so, that index can be pulled by query plan in queries by account id.

**Review by bartekn — APPROVED** [review]
LGTM! Do you have any performance stats for this change? Not required, just wonder what's the speed improvements in prd vs stg with mirroring turned on.

**Comment by sreuland** [comment]
@bartekn , yes, from report on #4455 , `/claimable_balances/{cb_id}/transactions`, [tested on stg, saw response times go from 10+ seconds to sub-second](https://github.com/stellar/go/issues/4455#issuecomment-1182612905) with the indexes in place.

**Comment by 2opremio** [comment]
Any idea of how much do the indices occupy?

**Comment by sreuland** [comment]
> Any idea of how much do the indices occupy?

each index created on stg(with pubnet history from genesis), [took about 6GB of size](https://github.com/stellar/go/issues/4455#issuecomment-1183533112).

**Pull request merged**
