### PR TITLE
services/horizon: Account for overlapping sandwiches in EndSponsoringFutureReserves

### LINKED ISSUE #2989: Invalid begin_sponsor when multiple sponsoring sandwiches in a transaction
### What version are you using?

`protocol-14` branch.

### What did you do?

Submit a transaction with multiple sponsorships:
```
BEGIN_SPONSORING_FUTURE_RESERVES (source: A, sponsored_id: B)
BEGIN_SPONSORING_FUTURE_RESERVES (source: C, sponsored_id: D)
END_SPONSORING_FUTURE_RESERVES (source: B)
END_SPONSORING_FUTURE_RESERVES (source: D)
```

### What did you expect to see?

`begin_sponsor` fields on both `EndSponsoringFutureReserves` operations are the same.

### What did you see instead?

`begin_sponsor` fields should be different (point to actual sponsor).

I think we need to check IDs here instead of finding the first Begin operation:
https://github.com/stellar/go/blob/9f2f2e66f128fde9e321d226438e3861f9c6b391/services/horizon/internal/expingest/processors/operations_processor.go#L140-L151

### PR DESCRIPTION
**Pull request by 2opremio**
Closes #2989

### CODE REVIEW

**Review by bartekn — COMMENTED** [review]
I'm not sure this will work for all cases. I think both scenarios below are possible:
```
BEGIN_SPONSORING_FUTURE_RESERVES (source: A, sponsored_id: B)
BEGIN_SPONSORING_FUTURE_RESERVES (source: C, sponsored_id: D)
END_SPONSORING_FUTURE_RESERVES (source: B) <-- B first
END_SPONSORING_FUTURE_RESERVES (source: D)
```
```
BEGIN_SPONSORING_FUTURE_RESERVES (source: A, sponsored_id: B)
BEGIN_SPONSORING_FUTURE_RESERVES (source: C, sponsored_id: D)
END_SPONSORING_FUTURE_RESERVES (source: D) <-- D first
END_SPONSORING_FUTURE_RESERVES (source: B)
```
I think we should simply compare `BEGIN.sponsored_id` with `END.source` to find the matching operation.

**Comment by 2opremio** [comment]
It does work in both cases. Check it :) Or I can add a specific test if you want.

> I think we should simply compare BEGIN.sponsored_id with END.source to find a matching operation.a

This on the other hand won't work in all cases since the there can be multiple prior sandwiches with the same Begin.sponsored_id and different source.

**Comment by 2opremio** [comment]
> I think we should simply compare `BEGIN.sponsored_id` with `END.source` to find a matching operation.

Also, this assumes that the transaction is well formed (i.e. that the matching `BEGIN_SPONSORING_FUTURE_RESERVES` operation does in fact sponsor the right account) but from what we have seen at https://github.com/stellar/go/issues/2987 , this may not be the case.

**Comment by 2opremio** [comment]
Let's have a call about this. Fons fears infinite textual discussions 👹 😨

**Comment by 2opremio** [comment]
I had a call with @bartekn and we concluded that:
1. Indeed what @bartekn proposes (search by comparing `BEGIN.sponsored_id` with `END.source` ) is correct. I was wrongly assuming that sponsorship sandwiches had to be balanced and does my balanced-parenthesis approach doesn't.
2. What @bartekn proposes may not work if the transaction failed (e.g. like in the nesting example I show at https://github.com/stellar/go/pull/2994#issuecomment-690304101 ). We won't be gathering the begin operation sponsor when transactions fail.

**Comment by 2opremio** [comment]
@bartekn PTAL

**Review by abuiles — APPROVED** [review]

**Pull request merged**
