### PR TITLE
optimize account queries for payments and operations

### LINKED ISSUE #515: Fix slow query in Payments for Account endpoint
`history_operation_participants` has a composite index `hist_op_p_id` on `(history_account_id, history_operation_id)` fields. When running "payments for account" query:
```sql
SELECT hop.id, hop.transaction_id, hop.application_order, hop.type, hop.details, hop.source_account, ht.transaction_hash FROM history_operations hop LEFT JOIN history_transactions ht ON ht.id = hop.transaction_id JOIN history_operation_participants hopp ON hopp.history_operation_id = hop.id WHERE hop.type IN ($1,$2,$3,$4) AND hopp.history_account_id = $5 AND hop.id > $6 ORDER BY hop.id asc LIMIT 10
```
Postgres query planner opt to use `history_account_id` part of the index and because  `history_operation_id` is not used in a query the execution was slow.

This can be fixed by changing the query to use `hopp.history_operation_id` instead of `hop.id` when filtering and ordering results. The query is equivalent to the previous one but is using all fields of `history_operation_participants.hist_op_p_id` index.

Initial fix in #439 but was closed because the code should be improved.

### PR DESCRIPTION
**Pull request by howardtw**
Close #515

### CODE REVIEW

**Comment by howardtw** [comment]
@bartekn I thought what reviewers didn't like is the way that we added a special flag in the query builder. It's not ideal to manipulate the method receiver's state (the query builder in this case) and worry about it in order to handle a special case. In this PR, I think it's ok to add an extra parameter in the function generating the SQL query, and it might be cleaner without introducing `OperationsForAccountQ`. What do you think?

**Comment by howardtw** [comment]
> Adding a special flag in the query builder for this use case feels wrong.

This PR doesn't introduce a special flag. From the engineering perspective, IMO this one is better than the approach in #439 and can avoid adding the complexity to the code path brought by adding `OperationsForAccountQ`. However, I haven't had a deep understanding of the data set referred in the following comment.
> data set (ops joined with txs and participants, rather than just ops joined with txs).

Maybe @tomerweller can weigh in. If you both think introducing `OperationsForAccountQ` is the way to go, I'm ok with it.

**Comment by bartekn** [comment]
I really don't think the approach in this PR is good from _separation of concerns_ point of view. The code like:
```go
ops.ForAccount(action.AccountFilter)
forAccount = true
```
looks like a duplicate code to me. With `forAccount` parameter in `Page()` method it's possible to set it to `true` in another context, ex. when using `ForTransaction`. Also, developers using `OperationQ` should not be required to know the internals of this struct, what `forAccount` means and when it should be used and how it affects the query executed internally. This should be hidden from outside context.

I agree that @tomerweller could bring more detail.

**Comment by howardtw** [comment]
@bartekn yeah I'm still learning the code base, and I do appreciate all the insights you've been giving. I don't have a strong opinion on this, but it would still be good to hear what @tomerweller says.

**Comment by tomerweller** [comment]
I don't like this approach as it represents a leaky abstraction, for the reasons pointed out by @bartekn. The consumer of this API shouldn't be bothered with "remembering" which filters they applied when they page later.

In that sense, I prefer the #493 approach because it keeps this idiosyncratic behavior internal to the `OperationsQ` API and doesn't expose it to users. 

I believe the root cause of this design problem is that the query classes were built with the assumption that the data set you operate on is the same no matter which filters you apply. In this case the dataset is the operations table joined with the transactions table on operation id. However, the `forAccount()` function doesn't just filter the results, it also modifies the dataset (joins with the participants table). 

The immediate options as I see them: 
1. Introduce `OperationsForAccountQ` or with some other name. There will be some code duplication there but I think it will be the friendliest for future readers. 
2. Accept #493 as is. 
3. Modify #493 slightly so that instead of attaching a `forAccount bool` to the `OperationsQ` struct we attach an `opIdCol string`  which defaults to `hop.id` but changes to `hopp.history_operation_id` when an account filter is set. the `Page()` function will use whatever is set on the query struct. I think that will make it a bit more readable and not send the user on a thought experiment on why the account filter has a special flag. 

Probably leaning towards 3 but will happily approve any of the above (or better).

**Comment by bartekn** [comment]
@tomerweller I see your point now! I think that option 3 is easier as it requires small modifications to existing PR and adding some comments to explain reasoning behind this.

@howardtw Option 1 looks good too but 1) requires more time and 2) there are more `Q` structs that have the same issue (ex. connected to trades). So maybe we should first think more about the issue looking at other instances of the problem first.

So the way forward would be: 1) modify and merge #439 and 2) create a new issue where we can discuss how to solve the problem in the long term. Thoughts?

**Comment by howardtw** [comment]
Closing this one because of https://github.com/stellar/go/pull/829

**Pull request closed without merging**
