### PR TITLE
services/horizon: [v2.6.0] Add migration to rebuild trade aggregations when upgrading

### PR DESCRIPTION
**Pull request by paulbellamy**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Add back in the migration to rebuild the trade aggregations when running normal db migrations.

### Why

This seems like the easiest and simplest way to make sure node operators don't need to reingest all of history.

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Review by 2opremio — APPROVED** [review]
Did you test this will the full History?

**Review by bartekn — APPROVED** [review]
LGTM! I have an idea how we can do it at migration stage but prevent code duplication. We can add the method call that rebuilds the buckets to `services/horizon/internal/db2/schema.Migrate` (`MigrateUp` case).

**Comment by paulbellamy** [comment]
re: testing, yeah. When initially writing this, I ran it with full history, then ran the rebuild, and verified it generated the same data.

**Comment by paulbellamy** [comment]
re code duplication, i was thinking that db migrations shouldn't really change anyway. So we shouldn't need to maintain this, but potentially add another migration later if we need to change the format or w/e.

**Review by 2opremio — APPROVED** [review]

**Pull request merged**
