### PR TITLE
doc Use git clone instead of git checkout and suggest wrapping the po…

### PR DESCRIPTION
**Pull request by juandemanjon**
I am assuming this is a minor doc issue and I am not follow the pull request template. Also bear with me because this is my first contribution. I had encountered the doc issues when I was trying to follow the doc steps as newbie developer.

### CODE REVIEW

**Comment by 2opremio** [comment]
@juandemanjon would you mind signing the CLA?

Sorry for the unreasonably late response.

**Comment by juandemanjon** [comment]
@2opremio I did long time ago, but I just have signed the CLA again.

**Comment by 2opremio** [comment]
@cla-bot check

**Comment by 2opremio** [comment]
@juandemanjon I think the problem is due to the email you used in the commit, would you mind double-checking that's the identity you want and that you signed the CLA with that identity?

Thanks (And sorry again for the unreasonable delay)

**Comment by juandemanjon** [comment]
@2opremio I have dup the pull request at https://github.com/stellar/go/pull/3309

**Pull request closed without merging**
