### PR TITLE
Stream all payments

### PR DESCRIPTION
**Pull request by raymontag**
Adds a method to horizon clients which enables to stream
all payments and not only those for a certain account ID.

### CODE REVIEW

**Comment by raymontag** [comment]
Somehow I missed something in mocks.go, I will add this to the PR>

**Comment by robertDurst** [comment]
Looks good, thanks for the PR!

However, one thing. Have you considered how this may be tested? There has been a discussion going on in #261 regarding how to test streaming endpoints.

**Comment by epappas** [comment]
Hi guys, I'm jumping out of the blue, due to the reference of #261 .  Is there anyone working on this, otherwise I can pull-up the sleeves and do it? I think it has a bit delayed :)

**Comment by robertDurst** [comment]
@epappas can't comment on if anyone is working on this specific endpoint, however there are certainly other endpoints to tackle. If you need help finding a place to start, let me know. You can also reference this readme that I think is mostly up to date: https://github.com/stellar/go/tree/master/protocols/horizon

**Comment by terorie** [comment]
Bump, any update on this?

**Comment by epappas** [comment]
> Bump, any update on this?

@terorie I got busy with other stuff, and I didn't progress on this one. As I see there is not assignee, which I guess is being stalled.

**Comment by tomquisel** [comment]
Closing as new Go SDK is coming out soon.

**Pull request closed without merging**
