### PR TITLE
refresh quorum config based off https://www.stellarbeat.io/

### PR DESCRIPTION
**Pull request by anupsdf**

### CODE REVIEW

**Comment by anupsdf** [comment]
fyi, @stellar/platform-committers

**Review by mollykarcher — APPROVED** [review]

**Review by Shaptic — CHANGES_REQUESTED** [review]
How sure are we about these? The diff is super hard to read.

This is a pretty nasty attack vector, right? So let's be extra careful here. For example, the LOBSTR 2 (Europe) validator key seems to have changed:

```diff
-NAME="lobstr_2_europe"
-PUBLIC_KEY="GDXQB3OMMQ6MGG43PWFBZWBFKBBDUZIVSUDAZZTRAWQZKES2CDSE5HKJ"
+NAME="LOBSTR 2 (Europe)"
+PUBLIC_KEY="GCB2VSADESRV2DDTIVTFLBDI562K6KE3KMKILBHUHUWFXCUBHGQDI7VL"
```

**Comment by MonsieurNicolas** [comment]
There was a lot of drift over the years: Lobstr EU's key was changed about
10 months ago.
Config can be verified against stellarbeat (we use the same config
internally too)

**Comment by mollykarcher** [comment]
> The diff is super hard to read

> There was a lot of drift over the years

Indeed to both of these. I was equally annoyed by this when making these changes in other places. See the description on [this PR](https://github.com/stellar/kube/pull/2089) for a couple suggestions on how to make it slightly less painful.

**Review by Shaptic — APPROVED** [review]
Cool, ty for the sanity checks y'all :+1:

**Pull request merged**
