### PR TITLE
strkey: bitshift with unsigned int for Go 1.12 compatibility

### PR DESCRIPTION
**Pull request by balboah**
### What

Use unsigned int bitshift to be compatible with Go 1.12.

Quote from 1.13 release:

_Per the signed shift counts proposal Go 1.13 removes the restriction that a shift count must be unsigned. This change eliminates the need for many artificial uint conversions, solely introduced to satisfy this (now removed) restriction of the << and >> operators._

### Why

Go 1.12 is the most recent version used in Google App Engine.
To be able to use Stellar SDK with App Engine, this needs to be merged.

### Note

A convenient way to test with the older Go version:

```bash
docker run --rm -ti -v "$PWD":/app -w /app golang:1.12-alpine sh -c "apk --update add git build-base && go test ./strkey"
```

### CODE REVIEW

**Comment by balboah** [comment]
CLA signed

**Comment by ire-and-curses** [comment]
@cla-bot check

**Comment by ire-and-curses** [comment]
@balboah - thanks. This doesn't seem to be needed. According to [this](https://cloud.google.com/appengine/docs/standard/go/runtime), Google App Engine supports Go 1.12, 1.13 and 1.14.

> The Go 1.12+ runtime supports Go 1.12, Go 1.13, and Go 1.14, and it uses the latest stable release of the version you choose. App Engine automatically updates to new minor revisions upon app deployment, but it will not automatically update to a new major release.

**Comment by ire-and-curses** [comment]
@cla-bot check

**Comment by ire-and-curses** [comment]
@cla-bot check

**Comment by balboah** [comment]
Oh. My bad! Didn’t notice that “+”. I’ll try it out soon to confirm if it resolves the issue

På ons, sep. 16, 2020 vid 16:53, Eric Saunders <notifications@github.com> skrev:

**Comment by balboah** [comment]
Alright, sorry for the fuzz.
Specifying `runtime: go114` in the appengine app.yaml config does indeed fix this issue.

**Comment by ire-and-curses** [comment]
Cool - thanks for coming back with that info :+1:

**Pull request closed without merging**
