### PR TITLE
Minor captive-core refactorings

### PR DESCRIPTION
**Pull request by 2opremio**
I made some small while going through the new captive core code.

Namely, it renames `DBLedgerReader` to `LedgerBackendReader`.

### CODE REVIEW

**Comment by abuiles** [comment]
@2opremio I think this is superseded by @bartekn's PR here https://github.com/stellar/go/pull/2644

**Comment by 2opremio** [comment]
@abuiles true, at least partly.

**Comment by bartekn** [comment]
@2opremio it seems that https://github.com/stellar/go/pull/2644 is a superset of this PR. Do you mind reverting your changes to `exp/ingest/io`? It will save us some time resolving conflicts.

**Comment by 2opremio** [comment]
I am happy to wait on #2644 and resolve the conflicts

**Comment by bartekn** [comment]
@2opremio https://github.com/stellar/go/pull/2644 has been merged.

**Comment by 2opremio** [comment]
@bartekn PTAL

**Comment by bartekn** [comment]
Changed base branch to `release-horizon-v1.5.0` to be able to remove `captive-core` branch.

**Pull request merged**
