### PR TITLE
horizon: fix EffectRestoreFootprint enum

### PR DESCRIPTION
**Pull request by tsachiherman**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

The EffectRestoreFootprint had the same value as EffectBumpFootprintExpiration, which would generate uncertainties when processing effects.

### Why

Trivial

### Known limitations

n/a

### CODE REVIEW

**Review by chowbao — APPROVED** [review]

**Review by sreuland — APPROVED** [review]
not suggesting here/now, noticed no integration tests against these new ops yet, probably some tech debt we want to address at good point.

**Comment by tsachiherman** [comment]
> not suggesting here/now, noticed no integration tests against these new ops yet, probably some tech debt we want to address at good point.

Do we have integration tests against any of the other effects ?

**Comment by tsachiherman** [comment]
> not suggesting here/now, noticed no integration tests against these new ops yet, probably some tech debt we want to address at good point.

Do we have integration tests against any of the other effects ?

**Comment by sreuland** [comment]
> > not suggesting here/now, noticed no integration tests against these new ops yet, probably some tech debt we want to address at good point.
> 
> Do we have integration tests against any of the other effects ?

looks like some protocol/effects are indirectly verified through internal horizon integration tests which use the go sdk for api request/results, such as this one that refers to cb effects - https://github.com/stellar/go/blob/soroban-xdr-next/services/horizon/internal/integration/sponsorship_test.go#L721-L725, but is more incidental usage, for consideration in future, may be worthwhile to include some unit test coverage here in same protocols package to verify these.

**Pull request merged**
