### PR TITLE
Change the JSON representation of muxed ids to string

### LINKED ISSUE #3714: All muxed account IDs fields should be strings
### What version are you using?

2.4.1

### What did you do?

All IDs of muxed accounts returned by Horizon API should be of type `string` because they represent `uint64` variable. Rendering a JSON number can cause issues in JS.

https://horizon-testnet.stellar.org/transactions/905fd0d6412aab6ddcef0dcdd21c0ea6934e88856f79679fc4c80fe0f8213437/operations
```json
{
  "_links": {
    "self": {
      "href": "https://horizon-testnet.stellar.org/transactions/905fd0d6412aab6ddcef0dcdd21c0ea6934e88856f79679fc4c80fe0f8213437/operations?cursor=\u0026limit=10\u0026order=asc"
    },
    "next": {
      "href": "https://horizon-testnet.stellar.org/transactions/905fd0d6412aab6ddcef0dcdd21c0ea6934e88856f79679fc4c80fe0f8213437/operations?cursor=455665965346817\u0026limit=10\u0026order=asc"
    },
    "prev": {
      "href": "https://horizon-testnet.stellar.org/transactions/905fd0d6412aab6ddcef0dcdd21c0ea6934e88856f79679fc4c80fe0f8213437/operations?cursor=455665965346817\u0026limit=10\u0026order=desc"
    }
  },
  "_embedded": {
    "records": [
      {
        "_links": {
          "self": {
            "href": "https://horizon-testnet.stellar.org/operations/455665965346817"
          },
          "transaction": {
            "href": "https://horizon-testnet.stellar.org/transactions/905fd0d6412aab6ddcef0dcdd21c0ea6934e88856f79679fc4c80fe0f8213437"
          },
          "effects": {
            "href": "https://horizon-testnet.stellar.org/operations/455665965346817/effects"
          },
          "succeeds": {
            "href": "https://horizon-testnet.stellar.org/effects?order=desc\u0026cursor=455665965346817"
          },
          "precedes": {
            "href": "https://horizon-testnet.stellar.org/effects?order=asc\u0026cursor=455665965346817"
          }
        },
        "id": "455665965346817",
        "paging_token": "455665965346817",
        "transaction_successful": true,
        "source_account": "GAGYDQGN5FXRAWGDBD4EG5LRVGEM2APXIIU7LXRO6SIQVPQIHOR4KCBE",
        "type": "payment",
        "type_i": 1,
        "created_at": "2021-06-22T20:09:49Z",
        "transaction_hash": "905fd0d6412aab6ddcef0dcdd21c0ea6934e88856f79679fc4c80fe0f8213437",
        "asset_type": "native",
        "from": "GAGYDQGN5FXRAWGDBD4EG5LRVGEM2APXIIU7LXRO6SIQVPQIHOR4KCBE",
        "to": "GBJR3ISFRWXWGGMTAAGKCF43NPFII55YRKMGPNCO6EH2WO6MSN2ER5WA",
        "to_muxed": "MBJR3ISFRWXWGGMTAAGKCF43NPFII55YRKMGPNCO6EH2WO6MSN2EQAAAAAB2JLEZFLMGM",
        "to_muxed_id": 15647676714,
        "amount": "900.0000000"
      }
    ]
  }
}
```

### What did you expect to see?

```
        "to_muxed_id": "15647676714",
```

### What did you see instead?

```
        "to_muxed_id": 15647676714,
```

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #3714

### CODE REVIEW

**Comment by 2opremio** [comment]
This seems to work but I am not sure how. Unlike what I thought, we store the operation details (including the `_muxed_id` fields) in the DB as uint64. i.e:

```
func addAccountAndMuxedAccountDetails(result map[string]interface{}, a xdr.MuxedAccount, prefix string) {
	accid := a.ToAccountId()
	result[prefix] = accid.Address()
	if a.Type == xdr.CryptoKeyTypeKeyTypeMuxedEd25519 {
		result[prefix+"_muxed"] = a.Address()
		result[prefix+"_muxed_id"] = uint64(a.Med25519.Id)
	}
}
```

However, this PR changes the the JSON representation of response fields when extracted from the DB and it still works. Which means we can change the representation without reingesting (i.e. good news), but I can't explain why it doesn't break.

**Comment by 2opremio** [comment]
Note that we have an integration test exercising the `_muxed_id` accounts end to end (`TestMuxedAccountDetails()`), which is succeeding. That's why I am surprised about this change working.

**Comment by bartekn** [comment]
> However, this PR changes the the JSON representation of response fields when extracted from the DB and it still works. Which seems to mean that we can change the representation without reingesting (i.e. good news), but I can't explain why it doesn't break.

I think it works because you added a `string` tag. Check: https://golang.org/pkg/encoding/json/#Marshal
> The "string" option signals that a field is stored as JSON inside a JSON-encoded string. It applies only to fields of string, floating point, integer, or boolean types. This extra level of encoding is sometimes used when communicating with JavaScript programs.

**Review by bartekn — APPROVED** [review]

**Comment by 2opremio** [comment]
Uhm, I still don't get it. See https://play.golang.org/p/YlmjLzrVV6y

If I understand it properly. `addAccountAndMuxedAccountDetails()`stores it as `{ "foo_muxed_id": 1234}` into the DB. Shouldn't unmarhsaling fail when obtaining it from the DB (as in the playground example above?)

**Review by leighmcculloch — APPROVED** [review]
Nice catch. This seems like an unavoidable fix we need to make. At least the breaking change is coming before we've deployed the new Horizon, and quickly on the heels of anyone else having deployed it.

**Comment by bartekn** [comment]
Oh, I understand what you mean. This is working because we don't unmarshal directly into `protocols.*` structs but into `history.*` that are then converted using functions in `resourceadapter` package.

**Comment by 2opremio** [comment]
Alright, I can confirm my suspicion of this PR not working.  The `TestMuxedAccountDetails()` integration test was passing because I forgot to add a `,string` tag to the payment operation https://github.com/stellar/go/pull/3716/files#diff-e85c28c010ba102d83e882bf7b6df4519de9fc3ba10a0c9ae7c67f375ac54782R102 🤦

**Pull request merged**
