### PR TITLE
Use the ed25519 from golang.org/x/crypto

### PR DESCRIPTION
**Pull request by bobg**

### CODE REVIEW

**Comment by tomquisel** [comment]
Thanks so much for this @bobg! It looks like there are a few build issues & a conflict, could you check those out when you have a moment?

**Comment by howardtw** [comment]
Looks like @bobg has a newer version of `ssh/terminal/util.go` which has passed this [commit](https://github.com/golang/crypto/commit/687d4b818545e443c8ba223cbef20b1721afd4db). I think we will have update our outdated vendor packages in a systematic way. @tomquisel

**Comment by howardtw** [comment]
https://travis-ci.org/stellar/go/jobs/448480101#L571
^ looks like `dep ensure` is getting the latest version on master for `ssh/terminal/util.go`. I think we might be able to fix it by revisioning the `golang/x/sys` to at least this [commit](4ed4d404df456f81e878683a0363ed3013a59003) @bartekn @tomquisel

**Comment by tomquisel** [comment]
@howardtw cool, if there's a quick reversioning of `golang/x/sys` that you think will fix this, that sounds good. Go modules sound like a good long-term switch to make, but I'd rather avoid it right now.

**Comment by howardtw** [comment]
@tomquisel ok let me give it a try. I'll create an issue for switching to Go module as our future reference

**Comment by howardtw** [comment]
@bartekn I'm curious to learn why you wanted to do [this](https://github.com/stellar/go/pull/717/commits/17102ebb7dc8fae716b1d3b4d701f2b5aa4afdb2) and used this particular commit `8d1157a435470616f975ff9bb013bea8d0962067` for `golang.org/x/sys`

**Pull request merged**
