### PR TITLE
horizon: move cmd files into horizon/cmd

### LINKED ISSUE #871: Reorganize horizon directory
The current files in `services/horizon/` directory (`db.go`, `serve.go`, `version.go`, and `main.go`) can all be moved to a new directory `horizon/cmd`, where we use to spin up the horizon process.

### PR DESCRIPTION
**Pull request by howardtw**
This PR re-organizes files based on the cobra guideline [here](https://github.com/spf13/cobra#getting-started).

This PR:
1. renamed the original `main.go` to `root.go` and moved it to `/horizon/cmd`.
2. moved `db.go`, `serve.go`, and `version.go` to `/horizon/cmd`
3. added a new `main.go` in `/horizon`.
4. deleted the global variable `app *horizon.App`.
5. moved `rootCmd.AddCommand(dbCmd)` to `db.go`.
6. used `cobra.OnInitialize(initConfig)` and removed the call to `initConfig` from `initApp`

Close #871

### CODE REVIEW

**Comment by howardtw** [comment]
@brahman81 Can you take a look at this PR? Hope this PR won't break any current script. And did we make `horizon` and `horizon serve` the same on purpose?

**Comment by brahman81** [comment]
@howardtw I am not certain about the reasoning behind making `horizon` and `horizon serve` the same. 

@bartekn do you recall when this decision was made ?

With regards to potentially breaking scripts, are we changing the ordering/naming of the cli arguments here?

**Comment by howardtw** [comment]
> With regards to potentially breaking scripts, are we changing the ordering/naming of the cli arguments here?

Nope. Cli arguments are not changed in this PR. @brahman81

**Comment by bartekn** [comment]
LGTM!

> And did we make `horizon` and `horizon serve` the same on purpose?

I didn't write this code but I think it's kind of like _default_ command so that's why it's the same.

**Comment by howardtw** [comment]
To followup: https://github.com/stellar/go/pull/879

**Pull request merged**
