### PR TITLE
exp/keystore: add log-file and log-level flags

### PR DESCRIPTION
**Pull request by howardtw**
We haven't really started to log anything in a log file. With this PR,
dev-ops can easily create a file and use the flag `-log-file=LOG_FILE_PATH`
to start logging.

### CODE REVIEW

**Comment by accordeiro** [comment]
@howardtw from what I've seen from our regular deploy configs, we can simply send logs to stdout/stderr and the OS logging system pipes them to Kibana – so there's no need to actually define a log file. 

@brahman81 is this correct? Or does outputting to a file work for you as well?

**Comment by brahman81** [comment]
@accordeiro @howardtw both work, by default we ship syslog to ELK but if we log to a separate file we can more easily split/index individual log fields.

**Comment by howardtw** [comment]
@accordeiro I can see that horizon's log is being written to [here](https://github.com/stellar/puppet-v4/blob/master/environments/production/hieradata/primary_sg/stellar002_prd_horizon.yaml#L18) for example.

**Comment by accordeiro** [comment]
Sounds good – approved :)

**Pull request merged**
