### PR TITLE
Cap numHoursAgo at 672 hours (28 days)

### PR DESCRIPTION
**Pull request by tyvdh**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

[TODO: Short statement about what is changing.]

### Why
I'm using the ticker graphql endpoint to generate a list of meaningful assets but for this to truly be meaningful I will need 28 days of data not 7.

[TODO: Why this change is being made. Include any context required to understand the why.]

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by leighmcculloch** [comment]
@tyvdh I'll get the CLA message fixed for you.

**Comment by leighmcculloch** [comment]
@cla-bot check

**Comment by tyvdh** [comment]
I’m all for adding a test however I’m unlikely to be the guy to write it as I’m not a go developer nor am I familiar with this repo. I just need 28 days of data from the graphql endpoint 😬

**Comment by leighmcculloch** [comment]
I'll take a quick look.

**Comment by accordeiro** [comment]
Yeah, the Ticker is pretty light on tests – I mostly added to the more critical parts. Two comments about this change:

1. We should probably change the ingestion command to also backfill 28 days worth of trades. The default number of hours is defined here: https://github.com/stellar/go/blob/9c52f39a51e685a4fe0b383b38cde7f752b37ba1/services/ticker/cmd/ingest.go#L31
2. We should start ingesting orderbooks for 28-day relevant markets (vs only 7). This would be done here: https://github.com/stellar/go/blob/9c52f39a51e685a4fe0b383b38cde7f752b37ba1/services/ticker/internal/actions_orderbook.go#L15

**Comment by leighmcculloch** [comment]
I tried writing a small unit test for this area of code in tyvdh/go#1 but it doesn't do anything useful to test the full scope of what's required like the things @accordeiro pointed out, so I don't think the test is overly useful.

**Comment by 2opremio** [comment]
Do you still want to pursue this or shall we close it?

**Comment by tyvdh** [comment]
I mean it would still be nice to have but it's not urgent or something I have time to pursue. With the big query stuff we have now we can probably toss it or table it till we're looking at this again in the future.

**Comment by 2opremio** [comment]
I will close it until we take a look at it again.

**Pull request closed without merging**
