### PR TITLE
tools/stellar-key-gen: add tool to generate keys at command line

### PR DESCRIPTION
**Pull request by leighmcculloch**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Add tool to generate keys at command line.

### Why

When I'm running and testing services like webauth and recoverysigner either manually or when I'm writing Go tests I find myself needing to go to the lab to generate keys frequently. It would be helpful if there was a quick command to run to grab a new key. We might have something that does this already but I couldn't find anything. If there is I'm happy to discard this, otherwise this would be helpful.

### Known limitations

This tool is pretty limited scope, it doesn't do anything else other than output a random key. This is intentional, I'm not trying to start some new massive tool suite with it.

### CODE REVIEW

**Comment by leighmcculloch** [comment]
To test the cobra.Command properly I needed to update the cobra version. I haven't reviewed the cobra changes yet to understand if that and the other dependencies are safe. I'll circle back on that before merging.

**Comment by leighmcculloch** [comment]
Do you mean change the way it is tested instead of updating cobra? I can do that. Although we are four years behind on the latest version of cobra. I think it could be worth considering upgrading independent of this.

**Comment by bartekn** [comment]
Makes sense. AFAIR, you had script testing dependency updates, right?

**Comment by leighmcculloch** [comment]
>I think it will be much simpler to make `gen` return a string which is later printed

@bartekn I agree. It's a little more code but simpler and back to first basics without a reader needing to know so much about Cobra mechanics. I also think upgrading Cobra to the latest version would force an upgrade of Cobra in any application that is importing code in this repo which could be painful. I've updated the PR to not require a dependency change. Thanks!

**Pull request merged**
