### PR TITLE
exp/keystore: update spec

### PR DESCRIPTION
**Pull request by howardtw**
We decided to encrypt all users' public keys in case the keystore gets
hacked. As a result, each user will only have one row in the database of
the keystore, and all keys belonging to a user will be stored in the same blob.

This means the `/update-key` endpoint will be implemented on the client
side such that it will call `/load-keys` endpoint, decrypt the blob,
modified the blob, re-encrypt the blob, and finally call `/store-keys`
endpoint. Similar logic applies to `/remove-key` endpoint.

### CODE REVIEW

**Comment by howardtw** [comment]
We were leaning toward having CRUD endpoints before. However, given the design change, it doesn’t really give us too much of advantages of having an update endpoint since update/delete a single key becomes impossible for the backend. The only safety of an update endpoint is that the users will have to know whether they have an existing blob in our db.

I thought about allowing users to have multiple encrypters, but I think @tomquisel is leaning toward to making it simple for the MVP given that we don’t have such user case yet. And that’s something we can open up later.

**Comment by tomquisel** [comment]
Great discussion guys! Here's my take:

- `encrypterName` is a field that describes how the blob is encrypted, and is necessary to know how to decrypt it. The data model is one blob per user. If you did want to extend the data model to multiple blobs per user, you'd still want to support multiple of those blobs being encrypted with the same method, and having the same `encrypterName`. So, it's not really the kind of field to index/key on.
- I think it would be good to be REST compliant. As Howard points out, we moved away from CRUD since we're storing a compound blob that stores a list of key entries that can be added or removed, but to the server it all looks like storing the entire blob repeatedly. As as result, I think the best mapping of our use case onto rest would be `GET /keys` `PUT /keys` `DELETE /keys`. I'd probably prefer that over the proposal here.

@howardtw, is the idea behind this proposal that calling `GET /delete-keys` would delete the keys?

**Comment by howardtw** [comment]
I was actually thinking about POST everything for simplicity on both the client side and server side implementation. i.e. POST store-keys, POST load-keys, and POST delete-keys. But I’m open to other options.

**Comment by tomquisel** [comment]
Gotcha. It seems like it'll be more intuitive if we follow REST conventions, so I'd advocate for that.

**Comment by howardtw** [comment]
Ok get, put, delete on keys sounds good to me

**Comment by howardtw** [comment]
@tomquisel @accordeiro updated the spec in https://github.com/stellar/go/pull/1351/commits/410d3c81de83b845c6ff3c0a2c5a8af7aa56c209

**Comment by accordeiro** [comment]
Looks great to me! 🎉

**Pull request merged**
