### PR TITLE
Code standards

### PR DESCRIPTION
**Pull request by alpe**
Applied common Go tooling
* `go fmt`
* `goimports`
*  `go lint`: fixed dead code

### CODE REVIEW

**Comment by nullstyle** [comment]
Looks great!  Thanks for the work.

@bartekn rather than directly integrating into travis, I'd prefer we instead add a support script that performs this code normalization.  Then we can invoke it at any point it makes sense:  pre-commit or on-demand as needed.  I'd never want to consider a build broken because of unformatted code.

**Comment by dulanov** [comment]
Yes, ideally it should be automated by Travis, for example via `gometalinter`:

```console
go get -u github.com/alecthomas/gometalinter &
    gometalinter --install &
    gometalinter \
		--tests \
		--vendor \
		--vendored-linters \
		--disable=interfacer \
		--disable=maligned \
		--enable=gosimple \
		--enable=staticcheck \
		--enable=gofmt \
		--enable=goimports \
		--enable=lll \
		--enable=misspell \
		--cyclo-over=15 \
		--dupl-threshold=100 \
		--line-length=120 \
		--deadline=360s \
		./...
```

**Comment by bartekn** [comment]
> Then we can invoke it at any point it makes sense: pre-commit or on-demand as needed. I'd never want to consider a build broken because of unformatted code.

The problem with `pre-commit` and on-demand script is that we can't enforce all developers to run it. I think it's a good idea to enforce a code to be properly formatted.

We use JSLint in our JS repos and they make a build broken if there are problems with formatting.

**Comment by dulanov** [comment]
It's strange but still there are fmt errors after merge - https://goreportcard.com/report/github.com/stellar/go

image

**Comment by nullstyle** [comment]
> The problem with pre-commit and on-demand script is that we can't enforce all developers to run > it. I think it's a good idea to enforce a code to be properly formatted.

It's good to have properly formatted, but it isn't blocking.  

> We use JSLint in our JS repos and they make a build broken if there are problems with formatting.

I would argue that linting in javascript is _much_ more important than `go fmt` or `golint`.  Javascript's a much easier language to get wrong.

I'd be fine blocking the build for `go vet` violations, but considering a build broken because of a stylistic violations is just not worth the bureaucracy.

**Comment by tomerweller** [comment]
This looks great. Thanks @alpe 
I'm with @bartekn here. While breaking the build is a bit extreme, I like it better than giving developers the option to push code that's not properly formatted.

**Pull request merged**
