### PR TITLE
xdr: get data from LedgerEntryChange without panic

### PR DESCRIPTION
**Pull request by debnil**
### What

This PR creates panic-free versions of functions needed to extract `LedgerEntry`, `LedgerEntryType`, and other fields from `LedgerEntryChange`. 

### Why
In long-running, data-intensive applications, like the Hubble project, we want to avoid panics wherever possible. A panic on a single malformed input can abort the entire pipeline. A panic-free method to get various data from `xdr.LedgerEntryChange` helps reduce such possible failures.

### Known limitations
N/A

### CODE REVIEW

**Comment by ire-and-curses** [comment]
I discussed this a bit with @bartekn. We don't really agree with this idea of avoiding panics during ingestion.

Let's say your app receives a `LedgerEntry` with invalid type (it's not an account, trustline, offer or account data). This means that either your code is broken, there's memory corruption, or history archives have invalid data. In this case you really want to panic/crash the app because continuing can have a compounding effect, as derived data (e.g. current balance) becomes untrustworthy.

Effective Go mentions that `panic` should be used for unrecoverable errors. An invalid type of an entry is pretty much unrecoverable. You can skip it but then the data will not be complete. You can try again but the type won't change to a valid one.

For this reason Horizon (also a long-running, data-intensive app) takes the approach of blocking further access to endpoints if invalid ingestion occurs.

**Comment by debnil** [comment]
Interesting, that makes a good deal of sense to me. I'm going to tag @nikhilsaraf in this, in case there are any other benefits of eliminating panics that are separate to the above.

**Comment by leighmcculloch** [comment]
>you really want to panic/crash the app because continuing can have a compounding effect

An application might choose to panic if the program itself decides it is in an unrecoverable situation. It's also a pattern to use panics inside library code to short-circuit an internal process if that process has entered an unrecoverable state and it's easier to `panic` and `recover` than navigating error passing across go routines (the stdlib does this in some places).

But, it's not expected that libraries will intentionally crash an application if an error occurs, which is what @debnil is experiencing.

If the pipeline is going to use panics internally to short-circuit itself and keep that code slim, okay, it should still recover that panic and surface the error to the caller of the pipeline instead of expecting the application to wrap all calls to the ingestion functions in a `defer` `recover`.

**Comment by bartekn** [comment]
I think what we want to emphasize is that when an app receives a `LedgerEntry` with invalid type it means that other data received from history archives/ledger backend may be malformed too (due to corrupted history archive, reader bug, memory corruption or any other bug) and shouldn't be trusted.

I'm not against adding these methods but devs should use them only if they know how to handle the error properly. Ignoring such errors and continuing with the next ledger ingestion or simply skipping the ledger entries with invalid type can cause worse consequences than crashing an app. Maybe we should extend the godoc comments to explain how the error should be handled?

BTW, when it comes to use of `panic` we have discussions about this every month. We should agree on something so the code is consistent and everyone is happy using `panic` (or not) 😉.

> But, it's not expected that libraries will intentionally crash an application if an error occurs, which is what @debnil is experiencing.

Has this actually manifested in the code? Like, you received a `LedgerEntry` with invalid type?

**Comment by debnil** [comment]
@bartekn: I haven't received a `LedgerEntry` from archives with invalid type, the only ones that have  occurred have been handcrafted, malformed examples when I was testing functions used in the pipeline. I definitely get your point though: in production, erroring out avoids significant damage to the quality of the dataset. 

Curious what @nikhilsaraf's perspective on this is.

**Comment by debnil** [comment]
Made unnecessary by changes in our approach to data analytics.

**Pull request closed without merging**
