### PR TITLE
 clients/horizonclient fix request timeout

### PR DESCRIPTION
**Pull request by olegfomenko**
Fix for  clients/horizonclient/client.go sendRequestURL method context timeout. 

Redundant multiply horizonTimeout on time.Second creates timeout equal to 10^18 nanoseconds (if horizonTimeout was set as 1 second (by default) )

### CODE REVIEW

**Comment by olegfomenko** [comment]
@cla-bot check

**Comment by olegfomenko** [comment]
@cla-bot check

**Comment by ire-and-curses** [comment]
@cla-bot check

**Review by tamirms — APPROVED** [review]

**Comment by ire-and-curses** [comment]
Thanks for this @olegfomenko!

**Pull request merged**
