### PR TITLE
services/horizon Add version to log entries

### PR DESCRIPTION
**Pull request by wolmi**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### Summary

This PR is related to the issue #1683 adding version on the log entries of horizon. All logs will include `version=x.y.z`at the beginning of the line

### Goal and scope

The `apkg.Version()` has added on every log entry and hlog with the specified fromat to allow easy parsing of logs.

### Summary of changes

Added `version=%s` at the begging  of every call to Printf or Fatalf also added de call to `apkg.Version()` on eache call to print the value

### Known limitations & issues

The hlog library has not been changed because is not clear if it is on the scope of the isssue #1683 that we are pretending to solve

### What shouldn't be reviewed

Check if the format is correct and has the expected log output.

### CODE REVIEW

**Comment by bartekn** [comment]
Thanks for taking the time to work on this PR! We can do it much simpler. In `App.init`:
```go
log.DefaultLogger = log.DefaultLogger.WithField("version", apkg.Version())
```
Then all logs that are generated using `log.DefaultLogger` will have `version` field.

**Comment by wolmi** [comment]
I've reverted the commits where I put the log per file and moved as per your advice to app.go, is it the correct place?

I've also signed de CLA.

**Comment by ire-and-curses** [comment]
@cla-bot check

**Comment by ire-and-curses** [comment]
@wolmi looks like you're missing an import (so builds are failing), and there's a changelog conflict. Could you fix, and then we can re-review?

**Comment by abuiles** [comment]
@wolmi Thanks! Can you please rebase against the branch release-horizon-v0.23.0? The changelog update should be under v0.23.0 which is our next release.

**Comment by 2opremio** [comment]
Do you still want to pursue this or shall we close it?

**Pull request closed without merging**
