### PR TITLE
xdr and historyarchive: Remove XDR decoder allocations from XdrStream

### PR DESCRIPTION
**Pull request by 2opremio**
Also:
* Move Uint32Ptr into test file (it was only used for testing)
* Tidy up EncoderTo and DecoderFrom interfaces

### CODE REVIEW

**Comment by 2opremio** [comment]
@bartekn , @tamirms Please let me know if there are other places in Horizon which would benefit from a similar pattern.

**Review by tamirms — APPROVED** [review]

**Comment by tamirms** [comment]
> Please let me know if there are other places in Horizon which would benefit from a similar pattern

I found 3 more places which I think would benefit from using decoders / encoders:

(1) https://github.com/stellar/go/blob/master/ingest/ledgerbackend/buffered_meta_pipe_reader.go#L96
This is where we read ledgers from the captive core pipe

(2) https://github.com/stellar/go/blob/master/ingest/ledgerbackend/remote_captive_core.go#L115
This is where we read ledgers from the http response that we receive from the remote captive core server

(3) https://github.com/stellar/go/blob/master/exp/services/captivecore/internal/api.go#L184
This is where we serialize the ledger into base 64 before in the captive core server

**Comment by 2opremio** [comment]
Great, I will take a look

**Comment by 2opremio** [comment]
I optimized the captive core pipe decoding at https://github.com/stellar/go/pull/4077

About remote captive core, I saw there was json marshaling/unmarshaling  involved which is done through reflection.

I don't think that an extra XDR decoder allocation is going to make a big difference before optimizing the json encoding. I may be wrong though so @tamirms feel free to take a look at it yourself (now I am curious).

**Pull request merged**
