### PR TITLE
cmd: limit global flags displayed on cli help output

### LINKED ISSUE #5022: services/horizon/flags: refined cli help content
### What problem does your feature solve?
current help output printed to console from `stellar-horizon -h` and sub-commands  like`stellar-horizon <sub-command> -h` prints all Global Flags in any case, many of which are not relevant within specific sub-commands.

the Global Flags section can be noisy, making difficult to understand what parameters are relevant for each specific sub-command like `serve`, `db`, `ingest`, `record-metrics`

### What would you like to see?
reduced cli help output, less copy, but what is printed is more concise to context.

* `stellar-horizon -h` doesn't print Global Flags, just the sub-commands available and new 'best practices' blurb to recommend using environment variables overall.

* `stellar-horizon <sub-command> ... -h`, doesn't print Global Flags, just the flags relevant for the `<sub-command>`'s given, i.e. the help output for `stellar-horizon db init` vs `stellar-horizon db reingest`

### PR DESCRIPTION
**Pull request by sreuland**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What
* Limit which global flags will display on `-h` cli output to when it's only relevant to the command's general roles that it may be performing 'ingestion', 'db update tool' or 'api server'.
* Don't show global flags on help output when the most specific sub-command still has child sub-commands, limit help output to just list of available sub-commands.

### Why

The global flags are a fixed set of parameters and get displayed as a single large block on the console help output for any help request regardless of the level of `horizon` command. Since it's a fixed list, many of the global parameters tend to not be relevant to the context of command being requested by help and therefore can be somewhat mis-leading.

Closes #5022 

### Notes for review:

Start here, the solution overrides the cobra HelpFunc:
https://github.com/stellar/go/pull/5077/files#diff-7ad09d8c6e6a91967287e26e0343f0262ed02aa9fab85a0741cf665eeab514efR52

Some screen shots of help output from this PR on top, and current horizon on bottom.  
  
<br>
`stellar-horizon -h`. 

Screen Shot 2023-10-05 at 8 40 06 PM

<br>
<br>
`stellar-horizon ingest -h`. 

Screen Shot 2023-10-05 at 8 41 50 PM
<br>
<br>
Screen shot of help output from this PR on left, and current horizon on right:  
`stellar-horizon db reingest range -h`. 

Screen Shot 2023-10-05 at 8 50 39 PM

### CODE REVIEW

**Review by aditya1702 — APPROVED** [review]
LGTM. Just need to resolve the merge conflicts.

**Review by urvisavla — COMMENTED** [review]
The changes look great!  The only thing I noticed is that `horizon db reingest` displays all global flags, whereas `horizon db reingest -h` does not. I believe `horizon db reingest` cannot be used on its own without specifying a range so I expected the output of `horizon db reingest` to same as `horizon db reingest -h`

**Comment by sreuland** [comment]
> The changes look great! The only thing I noticed is that `horizon db reingest` displays all global flags, whereas `horizon db reingest -h` does not. I believe `horizon db reingest` cannot be used on its own without specifying a range so I expected the output of `horizon db reingest` to same as `horizon db reingest -h`

good catch, yeah, I think cobra is routing through a 'usage' output function there, so the hooked 'help' didn't get a chance to run, I'll look into it further to see if can capture that path, thanks!

**Comment by sreuland** [comment]
> The changes look great! The only thing I noticed is that `horizon db reingest` displays all global flags, whereas `horizon db reingest -h` does not. I believe `horizon db reingest` cannot be used on its own without specifying a range so I expected the output of `horizon db reingest` to same as `horizon db reingest -h`

@urvisavla , fortunately, cobra allowed overriding the usage output in same way as help output, so i was able to apply the same global flags behavior in this case of usage - https://github.com/stellar/go/pull/5077/commits/deca1ccebc4e03a2165f67215a120e3c6b396328

**Review by urvisavla — APPROVED** [review]

**Pull request merged**
