### PR TITLE
require strkey length is divisible by 8

### LINKED ISSUE #1804: strkey: check key is not padded
In stellar-core when decoding a strkey we check that the strkey encoded is not padded by checking that the length is divisible by eight. We don't do this check in the Go SDK, so the Go SDK can successfully decode strkeys that are padded with `===`s.

The `strkey.Decode` function should be changed to disallow padding by requiring the length is divisible by `8`.

Example of same logic in `stellar-core`:
https://github.com/stellar/stellar-core/blob/27387f0/src/crypto/StrKey.cpp#L41-L73

This issue is similar to #1796, but unrelated because it applies to all strkeys and that other issue applies only to public and secret keys that are encoded as a strkey.

### PR DESCRIPTION
**Pull request by ysz**
closes #1804

### CODE REVIEW

**Comment by ysz** [comment]
CLA signed.

**Comment by ire-and-curses** [comment]
@clabot check

**Comment by ire-and-curses** [comment]
@cla-bot check

**Comment by abuiles** [comment]
@cla-bot check

**Comment by 2opremio** [comment]
This is no longer necessary after https://github.com/stellar/go/pull/2491 .

**Pull request closed without merging**
