### PR TITLE
services/{bridge,compliance}: delete

### PR DESCRIPTION
**Pull request by leighmcculloch**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What
Delete the `bridge` and `compliance` services, and the internal package that contained code shared by only those two services.

### Why
The bridge and compliance services were built to facilitate [SEP-3]. The SEP was deprecated in December 2019. We don't seem to be making changes to bridge and compliance and from what I can tell they aren't being actively supported anymore.

We're making changes to the SDKs in the monorepo and bridge and compliance both need updating, but that effort seems unnecessary given the services aren't otherwise being maintained.

### Known limitations

N/A

[SEP-3]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0003.md

### CODE REVIEW

**Comment by leighmcculloch** [comment]
If this PR is approved for merging I will extract the two services at the commit just before this is merged into a single repository named `bridge-compliance` at https://github.com/stellar-deprecated and retain their Git history in that extraction as was done with other projects.

**Comment by leighmcculloch** [comment]
We still have these developer docs talking about SEP-3, so maybe SEP-3 is not really deprecated. @rice2000 Can I delete this docs page too?

https://www.stellar.org/developers/guides/compliance-protocol.html

Also, this website is still alive supporting compliance, who runs that?

https://gostellar.org

**Comment by tomquisel** [comment]
I think @brahman81 knows about https://gostellar.org ?

**Comment by leighmcculloch** [comment]
@tomerweller Gave me a 👍off Github.

**Comment by tomerweller** [comment]
@leighmcculloch that page already has a deprecation notice and the new docs are about to go live. So I wouldn't bother. However, @rice2000 if the new docs will take a while, maybe it's worth removing the link to the compliance page from the navigation pane.

**Comment by rice2000** [comment]
The navigation page is generated by a fairly gnarly script, so figuring out how to delete this may take some digging, but 'll look into it.  If it's not a rabbit hole, I'll do it.  If it is, the deprecation warning may have to suffice.  I don't think this page is many views at the moment.

**Comment by leighmcculloch** [comment]
For the sake of these deprecated services being easily accessed and revived by anyone else who might be interested in them I have extracted the Git history for those services from this repository and made them compilable in isolation over at https://github.com/stellar-deprecated/bridge-compliance.

**Comment by rice2000** [comment]
Ingenious.

**Pull request merged**
