### PR TITLE
[CAP 35] Update XDR definitions according to the latest CAP35 changes

### PR DESCRIPTION
**Pull request by 2opremio**
See https://github.com/stellar/stellar-protocol/pull/878 for more details.

Fixes https://github.com/stellar/go/issues/3448

### CODE REVIEW

**Comment by 2opremio** [comment]
The CAP35 integration tests are failing because the captive core binary used needs to be updated with the latest changes at https://github.com/stellar/stellar-core/pull/2918

@sisuresh please let me know when a debian package is available. Thanks

**Comment by bartekn** [comment]
@sisuresh @2opremio  any updated on the debian package?

**Comment by sisuresh** [comment]
> @sisuresh @2opremio any updates on the debian package?

I should have one ready sometime next week. The final CAP-0035 PR is close to being merged. I can also create a package off of that PR right now if that's preferable.

**Comment by 2opremio** [comment]
@sisuresh We are  planning to make a Horizon release this week, which (although protocol 16 isn't ready yet) will contain protocol 16 support. Thus, we would like to get this PR merge before that happens (otherwise we would be releasing half-baked support for protocol 16).

**Comment by sisuresh** [comment]
@2opremio The SetTrustlineFlags PR just had a few test related comments left, so I just created a package off of that. The package version is `15.3.0-498.7a7f18c.xenial~SetTrustlineFlagsPR~buildtests`. Please let me know if there are any issues with the build.

**Comment by 2opremio** [comment]
Thanks @sisuresh !!

This is finally ready for review.

**Review by bartekn — APPROVED** [review]

**Pull request merged**
