### PR TITLE
Add testing for LoadeTrades() using Golang testing and testify package

### PR DESCRIPTION
**Pull request by michaelran16**

### CODE REVIEW

**Comment by michaelran16** [comment]
First of all, the commit https://github.com/stellar/go/pull/421/commits/ce9a2c61c2d72fc6654de2121d81fad37a16f3d2 would not work. 

This code is using Golang testing and testify library. Running 'go test', this is the error I'm getting:
```
GOROOT=/usr/local/Cellar/go/1.10.1/libexec #gosetup
GOPATH=/Users/michaelran/go #gosetup
/usr/local/Cellar/go/1.10.1/libexec/bin/go test -json ./... #gosetup
=== RUN   TestError_ResultCodes
--- PASS: TestError_ResultCodes (0.00s)
=== RUN   TestError_Envelope
--- PASS: TestError_Envelope (0.00s)
=== RUN   TestHorizon
Running Suite: Package: github.com/stellar/go/horizon
=====================================================
Random Seed: 1524679590
Will run 14 of 14 specs

••••••••••••••
Ran 14 of 14 Specs in 0.002 seconds
SUCCESS! -- 14 Passed | 0 Failed | 0 Pending | 0 Skipped --- PASS: TestHorizon (0.00s)
=== RUN   TestLoadTrades
--- FAIL: TestLoadTrades (0.62s)
	mock.go:384: ❌	LoadTrades(horizon.Asset,horizon.Asset,int,int,horizon.Limit,horizon.Order)
	mock.go:398: FAIL: 0 out of 1 expectation(s) were met.
			The code you are testing needs to make 1 more call(s).
			at: [main_test.go:332]
FAIL
FAIL	github.com/stellar/go/clients/horizon	0.647s

Process finished with exit code 1
```
Appearantly, DefaultTestNetClient.LoadTrades() is not enough to satisfy the AssertExpectations() in testify framework. 
```
// AssertExpectations asserts that everything specified with On and Return was
// in fact called as expected.  Calls may have occurred in any order.
```
Need some help here to have the correct testing, @nullstyle and @bartekn, @tomerweller, @nikhilsaraf

**Comment by nikhilsaraf** [comment]
@michaelran16 you should run tests like this:
> go/src/github.com/stellar/go> ./support/scripts/run_tests

**Comment by nullstyle** [comment]
@nikhilsaraf that's the command to run the entire test suite, but we should be maintaining the ability to run single tests via `go test`.   If the issue truly is that he ran the test in isolation, then we should consider it a bug with our testing system IMO.

**Comment by nullstyle** [comment]
So @michaelran16 the error you are getting isn't an error:  It's an actual test error.  I don't exactly know where you got that test code from, but it has got several bugs in it.   I'll follow up with some specific guidance after we get through with our all hands.

**Comment by nullstyle** [comment]
See https://github.com/stellar/go/blob/master/clients/stellartoml/client_test.go#L24 as an example of how you want to write your client tests.  Notice, we mock out the http responses, not the calls to the client themselves.

**Comment by michaelran16** [comment]
replaced with https://github.com/stellar/go/pull/428

**Pull request closed without merging**
