### PR TITLE
doc Use git clone instead of git checkout and suggest wrapping the po…

### PR DESCRIPTION
**Pull request by juandemanjon**
…stgres URL with single quotes

I am assuming this is a minor doc issue and I am not follow the pull request template. Also bear with me because this is my first contribution. I had encountered the doc issues when I was trying to follow the doc steps as newbie developer.

### CODE REVIEW

**Comment by 2opremio** [comment]
@cla-bot check

**Comment by 2opremio** [comment]
@juandemanjon thanks for the continued effort! Unfortunately it doesn't seem you signed the CLA with the mail email associated to your _@juandemanjon_ account

**Comment by ire-and-curses** [comment]
@cla-bot check

**Comment by ire-and-curses** [comment]
@2opremio he did sign the CLA, but there is a manual step required on our side to connect the dots.

> update the clabot-config with their GitHub Username,

All working now.

**Review by ire-and-curses — APPROVED** [review]

**Comment by ire-and-curses** [comment]
@juandemanjon Thanks for your contribution! Hope to see you again! The CLA will just work next time ;)

**Comment by 2opremio** [comment]
Ahhh, I thought it was fully automatic, apologies @juandemanjon

**Pull request merged**
