### PR TITLE
Add more information to horizon.Error message

### PR DESCRIPTION
**Pull request by bartekn**
Close https://github.com/stellar/go/issues/54

### CODE REVIEW

**Comment by jedmccaleb** [comment]
This doesn't go far enough I don't think. It should just return the response from horizon. Why make them jump through this other hoop?

**Comment by bartekn** [comment]
Because you still would need to access `horizon.Error.Problem` to fetch the error cause.
```go
resultCodes := herr.Problem.ResultCodes()
switch resultCodes["transaction"] {
case "tx_bad_seq":
  // OK, I just need to update seqnum
case "tx_bad_auth":
  // Did I sign for correct network?
case "tx_internal_error":
  // Let's wait 60 seconds and try again...
// ...
}
```
You wouldn't parse error string to get this data.

**Comment by jedmccaleb** [comment]
I'm saying the text of the horizon response. I think in general people will just need to see what horizon returned. They won't need some object.

**Comment by bartekn** [comment]
For errors, you can do it like: `fmt.Printf("%+v", err.(*horizon.Error).Problem))`. It will print `horizon.Error.Problem` object that contains all necessary data. I mean the response body shouldn't be part of error message IMHO.

**Comment by jedmccaleb** [comment]
That code crashes. `panic: interface conversion: error is *errors.withStack, not *horizon.Error`
Why is it bad for the horizon response to be in the err? You can make err a struct right with one field being the actual response, right?

**Comment by bartekn** [comment]
> `panic: interface conversion: error is *errors.withStack, not *horizon.Error`

There was a bug, fixed in https://github.com/stellar/go/commit/cbb1882bee9996781a65d92c4ed8eaec55dd7dbd. It should work now.

> Why is it bad for the horizon response to be in the err?

I meant it should be part of the error string you get when you call `err.Error()`. It can be part of the error struct (see next).

> You can make err a struct right with one field being the actual response, right?

It's already there, but decoded into `Problem` field, and `Problem` struct contains all the fields from the error response. So in practice you have access to full error response but it's already parsed for you so you don't have to do it.

**Pull request merged**
