### PR TITLE
Use dep for dependency management

### LINKED ISSUE #565: cannot use hook.Entries (type []logrus.Entry) as type []*logrus.Entry in return argument
after import  package `"github.com/stellar/go/clients/horizon"`

compiler says
```
go/src/github.com/stellar/go/support/log/entry.go:125:14: cannot use hook.Entries (type []logrus.Entry) as type []*logrus.Entry in return argument
```

### PR DESCRIPTION
**Pull request by bartekn**
`glide` developers [recommend to migrate](https://github.com/Masterminds/glide#golang-dep) to `dep`.

Close #565.

### CODE REVIEW

**Comment by bartekn** [comment]
Let's wait with merging for @brahman81 to come back to update build scripts.

**Comment by Tronglx** [comment]
Sorry if this comment is inconvenience, but i clone the newest source but when i run command "dep ensure -v", it is hang forever, I can't install dependency. I re-run above command but it alway hang and can't reach to 97/97 packages. Do you have anysolution for this case?
stellar-get-dep

**Comment by Tronglx** [comment]
I'm using the latest version. I try fix it by self.
Thank you!

**Comment by Lawrence-Windsor** [comment]
Just struggling to actually get this to run with an issue, seems like its to do with th ethereum repo. When i run `dep ensure -v` i get the below. it just cant seem to clone the repo, i could say i have tried all suggestions under the sun. Anyone know what the issue is, i had no prior issues using glide but man dep is causing me way too much headache.

`....
(45)  ? attempt github.com/ethereum/go-ethereum with 4 pkgs; 166 versions to try
(47)      try github.com/ethereum/go-ethereum@2
(47)  ✗   failed to fetch source for https://github.com/ethereum/go-ethereum: unable to get repository: Cloning into '/mnt/c/Users/winds/go/pkg/dep/sources/https---github.com-ethereum-go--ethereum'...
(47)    POST git-upload-pack (gzip 8390 to 4019 bytes)
(47)    remote: Enumerating objects: 75236, done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
(47)    fatal: The remote end hung up unexpectedly
(47)    fatal: early EOF
(47)    fatal: index-pack failed
(47)    : command failed: [git clone --recursive -v --progress https://github.com/ethereum/go-ethereum /mnt/c/Users/winds/go/pkg/dep/sources/https---github.com-ethereum-go--ethereum]: exit status 128
(47)      try github.com/ethereum/go-ethereum@v1.8.17
^CSignal received: waiting for 1 ops to complete...
(47)  ✗   failed to fetch source for https://github.com/ethereum/go-ethereum: unable to get repository: Cloning into '/mnt/c/Users/winds/go/pkg/dep/sources/https---github.com-ethereum-go--ethereum'...
(47)    POST git-upload-pack (gzip 8390 to 4019 bytes)
(47)    remote: Enumerating objects: 75236, done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
(47)    fatal: The remote end hung up unexpectedly
(47)    fatal: early EOF
(47)    fatal: index-pack failed
(47)    : command failed: [git clone --recursive -v --progress https://github.com/ethereum/go-ethereum /mnt/c/Users/winds/go/pkg/dep/sources/https---github.com-ethereum-go--ethereum]: signal: interrupt
...`

at which point i co a `ctrl c` to quit.

**Comment by bartekn** [comment]
> The remote end hung up unexpectedly
This looks like your connection issues, can you try again?

**Comment by Lawrence-Windsor** [comment]
Hey @bartekn trust me i doubt it is that, i have been doing this for 48 hrs, i even switched back to `glide` instead of `dep` and here is the new error via `glide install`

`
....
[INFO]  --> Fetching github.com/ethereum/go-ethereum
[WARN]  Unable to checkout github.com/ethereum/go-ethereum
[ERROR] Error looking for github.com\ethereum\go-ethereum\ethclient: Unable to get repository: Cloning into 'C:\Users\winds\.glide\cache\src\https-github.com-ethereum-go-ethereum'...
fatal: early EOF
fatal: the remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
: exit status 128
[WARN]  Unable to set version on github.com/ethereum/go-ethereum to . Err: Unable to retrieve checked out version: chdir C:\Users\winds\.glide\cache\src\https-github.com-ethereum-go-ethereum: The system cannot find the file specified.
[WARN]  Unable to set version on github.com/ethereum/go-ethereum to . Err: Unable to retrieve checked out version: chdir C:\Users\winds\.glide\cache\src\https-github.com-ethereum-go-ethereum: The system cannot find the file specified.
[WARN]  Unable to set version on github.com/ethereum/go-ethereum to . Err: Unable to retrieve checked out version: chdir C:\Users\winds\.glide\cache\src\https-github.com-ethereum-go-ethereum: The system cannot find the file specified.
...
`

i have tried all sorts from switching git to build with openssl as you can see above, instead of gnutsl as well as nearly 10 other things that in truth i dont even recall now. its only when it gets to this repo things go wrong. even if i do a 'go get github.com/ethereum/go-ethereum` i get this

`C:\Users\winds\go\src\github.com\stellar\go>go get -d github.com/ethereum/go-ethereum
# cd .; git clone https://github.com/ethereum/go-ethereum C:\Users\winds\go\src\github.com\ethereum\go-ethereum
Cloning into 'C:\Users\winds\go\src\github.com\ethereum\go-ethereum'...
fatal: early EOF
fatal: the remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
package github.com/ethereum/go-ethereum: exit status 128`

So i honestly dont get what the issue is, network related many other repo works, if its the size of the repo i already increased my git config to take up 2gb but no solution.

**Comment by Lawrence-Windsor** [comment]
@bartekn Did some more digging. Tried straight old `git clone`, i got the below error. as you can see the `ethereum-go` repo failed where the `stellar-go` passed. I honestly think its the repo but i cant figure out why. and if its the repo/provider of the repo its an issue with git there for glide or dep all wont work. I am think of pulling down the repo via zip and putting in the directly, but what will be the best way to remove the reference. This is only a small fix, i believe there is more to it

```
C:\Users\winds\go\src\github.com\stellar\go\vendor>git clone https://github.com/ethereum/go-ethereum.git
Cloning into 'go-ethereum'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

C:\Users\winds\go\src\github.com\stellar\go\vendor>git clone https://github.com/stellar/go.git
Cloning into 'go'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10267 (delta 1), reused 1 (delta 0), pack-reused 10260
Receiving objects: 100% (10267/10267), 17.49 MiB | 2.75 MiB/s, done.
Resolving deltas: 100% (7054/7054), done.
Checking out files: 100% (832/832), done.

C:\Users\winds\go\src\github.com\stellar\go\vendor>```

**Comment by Lawrence-Windsor** [comment]
Ok so back again, found a temp solution thought to mention it as it might help someone else. It seems to only work `dep ensure -v` but not with `glide install`. We still need a solution for traditional way but hey it works for now

1 - i create a mirror of `https://github.com/ethereum/go-ethereum.git` under my gitlabs accounts and expose that publicly at `https://gitlab.com/fakegroup/go-ethereum`

2 - within stellar-go source code, i find and replace all occurrence of `github.com/ethereum/go-ethereum.git` with `gitlab.com/fakegroup/go-ethereum`

Then i do `dep ensure -v` and everything works perfectly.

Note using `glide install` i get this error but not keen to dig in at this point i am alreadt behind

```
...
[INFO]  --> Fetching updates for gopkg.in/tylerb/graceful.v1
[WARN]  Download failed.
[ERROR] Update failed for gitlab.com/transferx-public/go-ethereum: Unexpected error while defensively updating submodules: exit status 1
[ERROR] Failed to do initial checkout of config: Unexpected error while defensively updating submodules: exit status 1
```

**Pull request merged**
