### PR TITLE
Merge release-horizon-v2.8.2 into master

### PR DESCRIPTION
**Pull request by bartekn**
I noticed that a few latest release branches were not merged. Any reason why? Was it because of XDR update PR?

### CODE REVIEW

**Comment by bartekn** [comment]
@tamirms @paulbellamy you were working on latest releases. Can you check the question above?

**Comment by tamirms** [comment]
> Was it because of XDR update PR?

I think the history is a bit messed up because for the 2.8.0 release I tried to exclude the XDR update.

**Comment by bartekn** [comment]
@tamirms @paulbellamy I resolved conflicts. I think it's fine to merge because XDR changes commit is now both in `master` and `amm` branch and the next release will contain `amm`. If we need to create a release without `amm` we can always create a new branch off `horizon-v2.8.2`.

**Comment by bartekn** [comment]
Ping

**Review by tamirms — APPROVED** [review]

**Pull request merged**
