### PR TITLE
service/horizon: git rm -rf service/horizon/internal/docs

### PR DESCRIPTION
**Pull request by paulbellamy**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

According to @rice2000 the docs there are old, crusty, unloved, ill-maintained, deprecated, and unused.

> The old docs on the website now redirect to the new docs.
> - @rice2000

### Why

Because I just wasted time editing them. 💣

### Known limitations

This doesn't update the PR template which pointed me at the bad old docs folder. Could we do that as well?

### CODE REVIEW

**Review by bartekn — APPROVED** [review]

**Review by bartekn — CHANGES_REQUESTED** [review]
Actually there are some files (like `internal/docs/captive_core.md`) that are still used so let me review it tomorrow.

**Comment by paulbellamy** [comment]
Oh, for example these pages: https://www.stellar.org/developers/learn/concepts/list-of-operations.html#allow-trust. 🤔 , though that should probably redirect to the matching page on the new docs?  Also discovered all the links in the java sdk comments are outdated as well...

**Comment by 2opremio** [comment]
@paulbellamy are you still pursuing this?

**Comment by 2opremio** [comment]
@paulbellamy ping

**Comment by paulbellamy** [comment]
No. Turns out some of the docs in there are still in use, but it's unclear which, so...

**Pull request closed without merging**
