### PR TITLE
exp/services/recoverysigner: use unique signing keys per registered account

### LINKED ISSUE #2343: exp/services/recoverysigner: add use of unique signing keys per registered account
### What
Add use of unique signing keys that are randomly generated for each account at registration, storing the signing secret key in Postgres, and using AWS KMS to encrypt the signing secret key. 

### Why
The application uses a single signing key for all accounts that are registered. The issue with this is that anyone who knows that single signer can determine what accounts are registered with a recoversigner server. This public association may be undesirable for a user using a recoverysigner.

### PR DESCRIPTION
**Pull request by howardtw**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

This PR adds the feature of using unique signing keys per registered account. The secret keys of the signers are encrypted and stored in the database.

### Why

The application uses a single signing key for all accounts that are registered. The issue with this is that anyone who knows that single signer can determine what accounts are registered with a recoversigner server. This public association may be undesirable for a user using a recoverysigner.

### Known limitations

N/A

Close #2343

### CODE REVIEW

**Comment by leighmcculloch** [comment]
@accordeiro So that it is easy to pickup where we left off, I've made a list of things to do before bringing this out of draft:
 - [ ] Add tests for the areas of code that aren't tested that use KMS https://github.com/stellar/go/issues/2750 
 - [ ] Add docs for how to use unique signing keys https://github.com/stellar/go/issues/2795
 - [ ] Add use of public key so service can startup without decrypting the keyset https://github.com/stellar/go/issues/2733
 - [ ] Support key rotation of unique signing keys https://github.com/stellar/go/issues/2631

**Comment by 2opremio** [comment]
Do you still want to pursue this or shall we close it?

**Comment by leighmcculloch** [comment]
We still plan to pursue this. Thanks @2opremio.

**Comment by 2opremio** [comment]
sorry for asking the same question again but do you still want to keep this open?

**Comment by leighmcculloch** [comment]
@2opremio I'm going to close this now because I don't know the answer to that and this PR is getting more out-of-date as time moves on. We still have the open issue here https://github.com/stellar/go/issues/2343 which I'll keep open until @shanzzam can chime in there.

**Pull request closed without merging**
