### PR TITLE
exp/orderbook: Include empty paths in path finding response

### PR DESCRIPTION
**Pull request by tamirms**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Fixes https://github.com/stellar/go/issues/4131

If the source asset is included in the list of destination assets we will include the empty path in the path finding response. For example:

If we receive the following `/paths/strict-send` query:

```
destination_assets=native,BTC:GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF

source_asset=BTC:GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF

source_amount=0.0005953
```

We will include the following empty path in the response:

```
{
        "source_asset_type": "credit_alphanum4",
        "source_asset_code": "BTC",
        "source_asset_issuer": "GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF",
        "source_amount": "0.0005953",
        "destination_asset_type": "credit_alphanum4",
        "destination_asset_code": "BTC",
        "destination_asset_issuer": "GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF",
        "destination_amount": "0.0005953",
        "path": []
      }
```
### Why

Simple payments (e.g. payments where an asset is transferred from one account to another without any conversions into another asset) are also valid path payments. Because the path finding endpoint is used to construct path payments we should not omit paths corresponding to simple payments.

### Known limitations

[N/A]

### CODE REVIEW

**Review by Shaptic — APPROVED** [review]
LGTM!

**Comment by marcinx** [comment]
Will this also work when a destination_account is given (instead of the list of destination assets) and vice versa with a given source_account (instead of source_assets)?

**Comment by tamirms** [comment]
@marcinx yes, it should work. the destination account is converted into a list of assets before reaching this code.

**Review by eliane345 — APPROVED** [review]
Desculpe o transtorno

**Pull request merged**
