### PR TITLE
Update horizon account response

### PR DESCRIPTION
**Pull request by bartekn**
Close https://github.com/stellar/go/issues/35

### CODE REVIEW

**Comment by MikeFair** [comment]
I'd like to test this out; one thing I noticed was the value I submitted seemed to get base64 encoded; but the Horizon Response wasn't automatically decoded.

I don't know which layer encoded the byte array value; but it should also decode it before the client tries to read it.

**Comment by MikeFair** [comment]
I manually applied the patch to my clients/horizon/responses.go file.
I can confirm that round tripping to the Stellar TestNet and back doesn't get decoded properly.

```
   passphrase := "ThePassPhrase"
   pair, err := keypair.FromRawSeed(hash.Hash([]byte(secret)))

   log.Println("SomeKey => " + pair.Address())
   SetData(pair.Address(), pair.Seed(), "SomeKey", []byte(pair.Address()))

   acct, _ := LoadAccount(pair.Address())
   log.Println("SomeKey => " + string(acct.Data["SomeKey"]))
```

produces
```
2017/02/13 09:13:24 SomeKey => GCBVL3SQFEVKRLP6AJ47UKKWYEBY45WHAJHCEZKVWMTGMCT4H4NKQYLH
2017/02/13 09:04:09 SomeKey => R0NCVkwzU1FGRVZLUkxQNkFKNDdVS0tXWUVCWTQ1V0hBSkhDRVpLVldNVEdNQ1Q0SDROS1FZTEg=
```

**Comment by bartekn** [comment]
You're right that data value is not decoded but we want structures in `response.go` to be in sync with the ones in [horizon](https://github.com/stellar/horizon) as we'll probably remove this file and `import` them directly from horizon in a near future. So you need to decode it using `encoding/base64`.

**Comment by MikeFair** [comment]
It's _really_ confusing that I don't Encode when submitting to the txn
Builder; but then I do Decode when reading it back.

Why isn't modifying LoadAccount to iterate and do the decode acceptable?
Same in the JS API

On Mon, Feb 13, 2017 at 9:28 AM, Bartek Nowotarski <notifications@github.com

**Comment by bartekn** [comment]
I understand that this can be frustrating but I really believe this should be changed in horizon repo. I will create a new issue there and hopefully it will be improved soon.

**Comment by MikeFair** [comment]
OH!! I get you now! Completely agreed!

I somehow got that by "compatible with horizon" you meant [horizon was
doing the right thing] && [the Go library should present that]

Not that the string should be translated in Horizon before being returned
(which I agree is where it "ought" to go).

Cool; I'm with you now! :)

**Comment by bartekn** [comment]
@MikeFair you can now use `MustGetData` and `GetData` methods on `Account` to get bytes value of data entry.

**Pull request merged**
