### PR TITLE
[Client] Introducing `StreamAllTransactions` to stream from the /transactions endpoint

### PR DESCRIPTION
**Pull request by epappas**
I am not sure if that's the right approach, or if the API naming was intended by the community,  but there is a misalignment with the naming of `StreamTransactions` & `account_transactions` according to the root endpoint [1].

In my case I's looking for a native call that can stream the transactions that are taking place in the network. But the `StreamTransactions` seems to be implementing the `account_transactions ` [2] endpoint. Leaving me with the option to propose an implementation of `StreamAllTransactions` method, with which we can achieve a generic stream of the network [3].

If I'm missing another call/way that the library is already implementing this, then please ignore & close this PR :)

Example of use;

```
var ctx, _ = context.WithCancel(context.Background())
var cursor = horizon.Cursor("now")
var horizonNetwork = horizon.DefaultTestNetClient

horizonNetwork.StreamAllTransactions(ctx, &cursor, func(t horizon.Transaction) {
	fmt.Println("Transaction", t)
})
```

Thanks

[1] https://horizon.stellar.org/
[2] https://horizon.stellar.org/accounts/{account_id}/transactions
[3] https://horizon.stellar.org/transactions

### CODE REVIEW

**Comment by nullstyle** [comment]
Hi @epappas could you include some tests for this PR?

**Comment by dexterlohnes** [comment]
Hi Scott / @nullstyle ,

I'm interested in picking up where @epappas left off with this PR since this is something I'd like to see implemented in the SDK. Could you possibly give some feedback as to how you'd like to see a test designed for a feature like this? I'm all for testing, but I'm not entirely sure where to begin with this; there are no tests pre-existing for the StreamTransactions endpoint, so there's little precedent to base tests off of. 

What would you suggest? Is the appropriate thing to test here that we are properly handling data in the expected format? If so, do we just copy a response from https://horizon-testnet.stellar.org/transactions, stick it in a variable, and test to make sure we can properly Unmarshal that into a transaction object?

If you can give me some guidance on this I'm happy to put this under test along with the original StreamTransactions function.

**Comment by dexterlohnes** [comment]
@nullstyle It certainly does. Thank you for the helpful response. I will do my best to write a test suite for this if possible. If it's at all possible for you to point me to any part of the code base that is under similar tests, it will help me a great deal since I'll be able to work a bit by analogy rather than starting from scratch which is a bit more difficult for me as an experienced programmer but a novice gopher.

**Comment by nullstyle** [comment]
While I'm not perfectly happy with this [example](https://github.com/stellar/go/blob/master/clients/stellartoml/client_test.go#L24), it's as close as i can get @dexterlohnes.  Sorry for taking so long to respond.

**Comment by epappas** [comment]
cc: @dexterlohnes, @nullstyle 

Hi both, really sorry for the radio silence.

So I did try to include some tests, but it seems the `httpmock` just can't handle streaming scenarios. I tried to clone the behaviour of another streaming case, but I realised none of the streaming methods is unit tested (apart of the example cases). I'll try to come back and debug why that's the case.

For now I've introduce an example case, in the tests.

As for the history, this is how far I got, in implementing the test case;

```
func TestStreamAllTransactions(t *testing.T) {
	hmock := httptest.NewClient()
	client := &Client{
		URL:  "https://localhost",
		HTTP: hmock,
	}

	hmock.On("GET", "https://localhost/transactions?cursor=now").ReturnString(200, orderBookResponse)

	cursor := Cursor("now")

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)

	err := client.StreamAllTransactions(ctx, &cursor, func(transaction Transaction) {
		defer cancel()

		assert.Equal(t, transaction.ID, "3389e9f0f1a65f19736cacf544c2e825313e8447f569233bb8db39aa607c8889")
		assert.Equal(t, transaction.PagingToken, "12884905984")
		assert.Equal(t, transaction.Hash, "3389e9f0f1a65f19736cacf544c2e825313e8447f569233bb8db39aa607c8889")
		assert.Equal(t, transaction.Account, "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7")
		assert.Equal(t, transaction.AccountSequence, "1")
		assert.Equal(t, transaction.FeePaid, "300")
		assert.Equal(t, transaction.Signatures[0], "SsKlst02jsaBp35vXlI300Qbz39+HbwwNDX/gfM+MwaG/dFF7bgqpkKsDAsh/qJDiN3NOW695IZB9Mj+JAsHBA==")
	})

	assert.NoError(t, err)
}
```

But the `objectBytes` in the `stream` method of `stellar-go/clients/horizon/client.go` was keep appearing as an empty slice.

I hope this gets you far enough?

**Comment by dexterlohnes** [comment]
Hmm... this is proving to be an interesting problem indeed!

It seems like the current test suite really lacks any ability to test streaming transactions in general, and that the test suite for the SDK overall could be made much more robust if we had proper infrastructure for supporting streaming scenarios. 

@nullstyle Do you think this is possible? More importantly, is it necessary or am I getting ahead of myself?

cc @robertDurst @tomerweller For your opinions on this matter.

If it comes down to needing to add the ability for our mock client to better emulate [Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), I'd be happy to work on it. I just want to make sure it's the proper direction before continuing on.

**Comment by nullstyle** [comment]
> Do you think this is possible? More importantly, is it necessary or am I getting ahead of myself?

Its definitely possible, and I'll look into adding stream testing, and feel .  Its 100% important for our test suite to cover these code paths.  I'll add some additional notes when I look into how I would test streaming endpoints. 

Thanks @dexterlohnes !


>  Also, while I appreciate testing as much as the next person, it does strike me that we're being asked to implement tests which are more robust than those covering any similar functionality to date. Perhaps there's a discussion to be had about the appropriateness of the requests?

I think framing this discussion as "Why don't you guys practice what you preach" is not appropriate.   "we're being asked to implement tests which are more robust than those covering any similar functionality to date"  is also not a fair characterization.  

We here at the SDF aim to have the entire published codebase tested.  Much of the code we ship will be employed -- if Stellar is successful -- in plenty of very sensitive environments.  We should aim for high quality software.  While there are gaps in our coverage, we should be closing them and not adding them.   While we have deficits in our code quality, we should be improving our quality and adding code to help ensure that quality going forward.  Furthermore, most gaps in our coverage are largely from resource and time contraints that I and the other platform devs have to contend with.  Lets take this specific example:  The horizon client package was extracted from the bridge server.  We wanted to make some sort client package available to go developers and while the code was tested as we developed the bridge server, it did not get an automated suite when it was extracted.  IIRC bartek probably had a million other things to work on;  He always does ;)

Let me address the "more robust" comment by making clear my testing expectations for any code we incorporate a little more clear.  At the highest level I hope a test suite aims to exercise each of the "input domains" of the system under test;  Think https://en.wikipedia.org/wiki/Boundary_testing.  For systems that have state and/or operating context, I expect there to be some considerations in the suite for the various modes that a system could be in.  There are plenty of examples in our monorepo that achieve this level of coverage.  Stepping down a bit in requirements/quality, I look for a testing path that stresses a proper use of the system under test;  The happy path. Additionally, I expect to see some coverage for the ways the system can fail.  Here's an example:  https://github.com/stellar/go/blob/master/clients/stellartoml/client_test.go#L28  While the coverage isn't 100% (I need to add a "the server timed out" test) you can clearly see how the system will handle a variety of failure modes.  At the lowest level of acceptability is the simple "happy path only" test, of which we probably have quite a few.  I know I've contributed a couple. I push back against this level of testing from outside/infrequent contributors;  By merging pull requests we at SDF are assuming maintenance responsibilities for that code, and I'm uncomfortable merging in that situation.  We're already overworked.  I'd rather instead that we ask outside contributors work to minimize ongoing maintenance costs by helping to improve our test suite as they work and contribute.

> It's a big demand of the community to support this though considering the lack of analogous tests to work from

For sure it is more tough to break trail, doubly so as a community contributor, but I don't think its asking too much of any contribution that it has some testing, regardless of the testing infrastructure we have previously stood up.  For example, If someone were to bring a PR with websocket support for horizon I would also expect them to contribute their own solution to testing that protocol.  I also don't think there is anything wrong with outsider contributors forking the repo and handling their needs themselves.  At some point in the future we can always find consensus on the appropriate solution for the SDF blessed version of the code and bring it into the fold. 

Of course, I'm open to discuss and incorporate feedback about our code acceptance process.  Nothing is set in stone :)

**Comment by dexterlohnes** [comment]
Thanks so much for your thoughtful response @nullstyle. Your comments on what exactly your expectations are for community contributions makes perfect sense, and certainly alleviates some of my confusion, and I can't agree more that it's not asking too much that any contribution has testing.

So, moving on to next steps: If you would prefer to work on something else, I'd be happy to tackle adding support for stream testing this coming week. I have plenty of free time at the moment, being between contracts, and it'd be an interesting exercise for me. Please just let me know! I'm happy to begin work on it and open a separate PR if desired.

**Comment by epappas** [comment]
@nullstyle 

Hey, excuse me about the tests. Yes the paths defenetaly need to be tested. I chose not to cover them, since there was not such a paradigm already set in the codebase, and introducing a new one would have been out of the scope of this PR.

Having said that, I’m very happy to jump and make a new PR that tests the other streaming calls (happy & error cases). Then merge it with this one and proceed.

**Comment by howardtw** [comment]
Great discussion above!

> I’m very happy to jump and make a new PR that tests the other streaming calls (happy & error cases). Then merge it with this one and proceed.

>  If you would prefer to work on something else, I'd be happy to tackle adding support for stream testing

@epappas @dexterlohnes enhancing how we test the streaming calls sounds good to me! 👍  I wonder if any of you guys have started to work on it

**Comment by epappas** [comment]
> @epappas @dexterlohnes enhancing how we test the streaming calls sounds good to me! 👍 I wonder if any of you guys have started to work on it

Hey @howardtw 

The feature should be pretty much completed, I'm using it on production. About the tests, I haven't done them on the Stellar repo, but in our own client. Feel free to finish it off.

**Comment by ire-and-curses** [comment]
@poliha Handing this over from me to you in case this is relevant to your current work.

**Pull request closed without merging**
