### PR TITLE
exp/orderbook: Optimize in memory path finding

### PR DESCRIPTION
**Pull request by tamirms**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`

### Thoroughness

* [x ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### Summary

When profiling the in memory path finding implementation I determined
that "math/big" operations was a significant bottleneck. Removing those operations resulted in an 8x improvement

### Goal and scope

Improve performance of in memory path finding

### Summary of changes

* remove use of big.NewRat in edges.go
* remove use of big.Int in price/main.go

### Known limitations & issues

N / A

### What shouldn't be reviewed

N / A

### CODE REVIEW

**Comment by tamirms** [comment]
it looks like bits.Mul64,  bits.Div64, and bits.Add64 are only supported in go 1.12 or higher. The current release of golang is 1.13

**Comment by bartekn** [comment]
> it looks like bits.Mul64, bits.Div64, and bits.Add64 are only supported in go 1.12 or higher. The current release of golang is 1.13

8x speed improvement sounds awesome and would be great to ship it ASAP. Maybe build tags could help? Go versions before 1.12 can use the old code and 1.12+ the new better code. https://medium.com/@theckman/version-constraints-and-go-c9309be15773

**Comment by tamirms** [comment]
> > it looks like bits.Mul64, bits.Div64, and bits.Add64 are only supported in go 1.12 or higher. The current release of golang is 1.13
> 
> 8x speed improvement sounds awesome and would be great to ship it ASAP. Maybe build tags could help? Go versions before 1.12 can use the old code and 1.12+ the new better code. https://medium.com/@theckman/version-constraints-and-go-c9309be15773

good idea, I'll look into this tomorrow!

**Comment by tamirms** [comment]
@bartekn can you take another look? I've updated the pr to have two implementations: one for go 1.12+ and one for go 1.10/1.11

**Pull request merged**
