### PR TITLE
services/friendbot: fix race condition in Bot.Pay

### PR DESCRIPTION
**Pull request by debnil**
This PR fixes an issue in the friendbot `Pay` function. Previously, the minion index and update were not being locked. As a result, tests that attempted concurrent access detected a race condition, as seen [here](https://circleci.com/gh/stellar/go/1985)

### CODE REVIEW

**Comment by nikhilsaraf** [comment]
@debnil What’s the error when running this test?

**Comment by bartekn** [comment]
I think that test is just fine because it simulates starting multiple go routines of `Pay` and that's happening in the `FriendbotHandler.loadResult` method. The [issue](https://circleci.com/gh/stellar/go/1985) detected by race detector is the following:
```
WARNING: DATA RACE
Write at 0x00c0000da7f8 by goroutine 9:
  github.com/stellar/go/services/friendbot/internal.(*Bot).Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot.go:28 +0x2d9
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay.func3()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:66 +0x50

Previous read at 0x00c0000da7f8 by goroutine 8:
  github.com/stellar/go/services/friendbot/internal.(*Bot).Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot.go:25 +0x181
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay.func2()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:61 +0x50
```
and it's really a race condition in `Pay` function:
```go
// Pay funds the account at `destAddress`.
func (bot *Bot) Pay(destAddress string) (*hProtocol.TransactionSuccess, error) {
	log.Printf("Selecting minion at index %d of max length %d", bot.nextMinionIndex, len(bot.Minions))
	minion := bot.Minions[bot.nextMinionIndex] // line 25
	resultChan := make(chan SubmitResult)
	go minion.Run(destAddress, resultChan)
	bot.nextMinionIndex = (bot.nextMinionIndex + 1) % len(bot.Minions) // line 28
	maybeSubmitResult := <-resultChan
	close(resultChan)
	return maybeSubmitResult.maybeTransactionSuccess, maybeSubmitResult.maybeErr
}
```
`bot.nextMinionIndex` is accessed from multiple go routines. We need to add a mutex that locks access to it to a single go routine.

**Comment by debnil** [comment]
@nikhilsaraf it's the data race documented in the trace below. This test was originally defined to create such a data race. I think we discussed why, because the `friendbot.Pay` function would be called through separate calls to a deployed endpoint, this would not happen with the deployed friendbot.

```
?   	github.com/stellar/go/services/friendbot	[no test files]
2019/06/12 18:15:33 Selecting minion at index 0 of max length 1
2019/06/12 18:15:33 Selecting minion at index 0 of max length 1
2019/06/12 18:15:33 Selecting minion at index 0 of max length 1
==================
WARNING: DATA RACE
Write at 0x00c0000da7f8 by goroutine 9:
  github.com/stellar/go/services/friendbot/internal.(*Bot).Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot.go:28 +0x2d9
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay.func3()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:66 +0x50

Previous read at 0x00c0000da7f8 by goroutine 8:
  github.com/stellar/go/services/friendbot/internal.(*Bot).Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot.go:25 +0x181
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay.func2()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:61 +0x50

Goroutine 9 (running) created at:
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:65 +0x5a6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162

Goroutine 8 (running) created at:
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:60 +0x552
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162
==================
==================
WARNING: DATA RACE
Read at 0x00c0000da7f8 by goroutine 8:
  github.com/stellar/go/services/friendbot/internal.(*Bot).Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot.go:28 +0x293
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay.func2()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:61 +0x50

Previous write at 0x00c0000da7f8 by goroutine 9:
  github.com/stellar/go/services/friendbot/internal.(*Bot).Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot.go:28 +0x2d9
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay.func3()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:66 +0x50

Goroutine 8 (running) created at:
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:60 +0x552
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162

Goroutine 9 (running) created at:
  github.com/stellar/go/services/friendbot/internal.TestFriendbot_Pay()
      /go/src/github.com/stellar/go/services/friendbot/internal/friendbot_test.go:65 +0x5a6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162
==================
--- FAIL: TestFriendbot_Pay (0.03s)
    testing.go:771: race detected during execution of test
FAIL
FAIL	github.com/stellar/go/services/friendbot/internal	0.043s
```

**Comment by debnil** [comment]
@bartekn thanks for the explanation and quick review!! I accidentally read the stack trace backwards and fixed the test alone, thinking that was sufficient.

**Comment by bartekn** [comment]
NP! Now we can review and merge https://github.com/stellar/go/pull/1398.

**Comment by nikhilsaraf** [comment]
locking access is the right fix, thanks @debnil and @bartekn

**Pull request merged**
