### PR TITLE
remove superfluous check

### PR DESCRIPTION
**Pull request by jedmccaleb**

### CODE REVIEW

**Comment by bartekn** [comment]
As discussed in https://github.com/stellar/horizon/issues/393 I think we should switch to checking `Title` field value.

**Comment by jedmccaleb** [comment]
It doesn't gain us anything to do this check.  Why not just look to see if the result_codes are there directly?

**Comment by bartekn** [comment]
Result codes are only added to "Transaction Failed" error, so when this method is called on any other error type it will return `ErrResultCodesNotPopulated` and I think it's fine. What do you think @nullstyle?

**Comment by jedmccaleb** [comment]
Maybe but what if that changes? Why not just look at the actual result codes instead of something else if the question is "are there result codes?"

**Comment by nullstyle** [comment]
I'm fine removing the check, although we should probably fix the test failures @jedmccaleb :)

**Comment by jedmccaleb** [comment]
ok I made a proper PR #75

**Pull request closed without merging**
