### PR TITLE
Add support to stream effects and operations

### PR DESCRIPTION
**Pull request by chr4**
This is an attemt to bring support to stream `/effects` to the Golang SDK.

Unlike in the JavaScript SDK this is not yet supported by the Go SDK (if I understood correctly).

Feedback welcome, especially concerning the `Effect` struct - I'm not sure whether I catched all properties, and wasn't sure where to get a complete list of them. I assembled them looking at a test file in the JS-JDK.

Code snipped to stream `/effects`:

```golang
package main

import (
	"fmt"
	"github.com/stellar/go/clients/horizon"
	"golang.org/x/net/context"
	"log"
)

func main() {
	client := horizon.DefaultTestNetClient
	cursor := horizon.Cursor("now")
	ctx := context.Background() // Stream indefinitly

	err := client.StreamEffects(ctx, &cursor, func(l horizon.Effect) {
			fmt.Printf("%+v", l)
	})

	if err != nil {
		log.Fatal(err)
	}
}
```

### CODE REVIEW

**Comment by chr4** [comment]
I've also added support for the `/operations` endpoint.

**Comment by matheusb-comp** [comment]
The `Operations` struct is lacking fields for some types of operations. I have proposed a [pull request](https://github.com/chr4/go-stellar-sdk/pull/1) with the changes.

However, the structs for `Effect` and `Operation` have been defined in the [`protocols/horizon`](https://github.com/stellar/go/commit/3d2c1defe73dbfed00146ebe0e8d7e07ce4bb1b6) package (added in #433). Should `client/horizon` use those, or will it keep using the structs defined in `responses.go`?

**Comment by chr4** [comment]
Thanks for pointing this out!

I'd be in favour of using officially provided structs. But after skimming over [protocols/horizon/effecs](https://github.com/stellar/go/blob/master/protocols/horizon/effects/main.go), if I understand correctly you'd have to first check what kind of effect incoming effects are before you can parse it into the respective struct?

e.g. you need to know that the incoming effect is of type `trustline_created` and then you can parse it into the `TrustlineCreated` struct? 

In the streaming case, though, it must be possible to parse all incoming effects into a struct no matter of its type. Or am I missing something here?

**Comment by matheusb-comp** [comment]
Could this be solved by having an `Operation` interface, that is passed to the operation handler. Then this interface can have methods to return the proper struct depending on the operation's `type_i` ?

#491 is about this, but the `Payment` struct wasn't changed yet.

**Comment by tomquisel** [comment]
Closing this as the new Go SDK is coming shortly.

**Pull request closed without merging**
