### PR TITLE
support/db: Switch driver from lib/pq to jackc/pgx

### PR DESCRIPTION
**Pull request by bartekn**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

This commit changes the Postgres driver used in `support/db` to `github.com/jackc/pgx`:
- [ ] Ensure connection pool is used.
- [ ] Check if able to reproduce the old driver errors in Horizon stg cluster.
- [ ] Explain why `lib/pq` is still imported.
- [ ] Ask other project leaders to check the changes and update their apps.

### CODE REVIEW

**Comment by leighmcculloch** [comment]
This is very intriguing. If this goes well I'd like to see how if it solves some of quirks we've had building using lib/pq, especially around inserting and selecting array types.

Are you thinking of using it via the database/sql interface, or use it directly?

If we use pgx without the database/sql interface, we probably need to make sure we use pgxpool so that a connection pool is in use, unless you intentionally hope to avoid it.

**Comment by bartekn** [comment]
@leighmcculloch this is a draft PR so we definitely don't have answers now and possibly we'll discard it. It won't be merged before all stellar/go users are OK with it. I just created it because we want to test it more in Horizon stg cluster.

There are two reasons for switching to `jackc/pgx`. First, `lib/pq` is no longer maintained so it slowly becomes a technical debt. Second, we actually run into a bug `lib/pq` that affects some Horizon queries. I can share a repro script with you.

**Comment by 2opremio** [comment]
@bartekn are you still pursuing this?

**Comment by 2opremio** [comment]
@bartekn ping

**Pull request closed without merging**
