### PR TITLE
clients/horizonclient: make HorizonTimeOut actually 60s

### PR DESCRIPTION
**Pull request by leighmcculloch**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Set the HorizonTimeOut time.Duration constant to 60 seconds.

Also remove some unnecessary casts to time.Duration because the values are already time.Durations.

### Why

It is currently set to 60 nanoseconds, but the comments claim it should be 60 seconds.

### Known limitations

N/A

### CODE REVIEW

**Comment by leighmcculloch** [comment]
So this PR isn't sufficient at fixing this confusion. It looks like the value does actually result in a timeout of 60s because of this: https://github.com/stellar/go/blob/b9639d223a4c2181dacc1ee311885c06c13890bd/clients/horizonclient/client.go#L60

This isn't good because the constant uses time.Durarion and so is expressing itself as 60 nanoseconds which we then multiply to be seconds. 

I won't merge this, I'll revisit this tomorrow.

**Comment by leighmcculloch** [comment]
The reason I caught this was because I used the value in a http.Client as well, and 60s caused an immediate timeout in the client.

**Comment by abuiles** [comment]
@leighmcculloch thanks!  I'll cherry-pick this commits into the horizonclient release 2.1

**Comment by leighmcculloch** [comment]
Fixing this is not so straight forward. In fact I don't see anyway of fixing this in a non-breaking way. To summarize:

- `HorizonTimeOut` is a `time.Duration` which means whatever value it is given is in nanoseconds. It is given the value `60`, so it is `60` nanoseconds.

- In `Client` `sendRequestURL` we multiple the value so that it becomes seconds.
   https://github.com/stellar/go/blob/b9639d223a4c2181dacc1ee311885c06c13890bd/clients/horizonclient/client.go#L42-L70 

- So in actual fact the value `60` is in seconds, but the type we're using is communicating it is in nanoseconds to a reader.

I think the safest thing to do here is to change the value from a `time.Duration` to an `int`. It's a breaking change because the type changes, but it's a bug, not a feature deviation. If it impacts someone, it's very possible it _should_ impact them  because it might be a bug for them too.

Thoughts?

**Pull request closed without merging**
